/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

package ft.mod.mfg.form;

import ft.mod.DModConsts;
import ft.mod.mfg.db.DDbLinePack;
import ft.mod.mfg.db.DDbLinePrep;
import ft.mod.mfg.db.DDbLinePrepItemFamily;
import ft.mod.mfg.db.DDbLinePrepLinePack;
import ft.mod.mfg.db.DDbVariable;
import ft.mod.mfg.db.DMfgUtils;
import ft.mod.mfg.db.DRowOption;
import java.awt.BorderLayout;
import javax.swing.border.TitledBorder;
import javax.swing.event.ChangeEvent;
import javax.swing.event.ChangeListener;
import sba.lib.DLibConsts;
import sba.lib.DLibUtils;
import sba.lib.db.DDbRegistry;
import sba.lib.grid.DGridColumnForm;
import sba.lib.grid.DGridConsts;
import sba.lib.grid.DGridPaneForm;
import sba.lib.grid.DGridRow;
import sba.lib.gui.DGuiClient;
import sba.lib.gui.DGuiConsts;
import sba.lib.gui.DGuiUtils;
import sba.lib.gui.DGuiValidation;
import sba.lib.gui.bean.DBeanForm;

/**
 *
 * @author Sergio Flores
 */
public class DFormVariable extends DBeanForm implements ChangeListener {

    private DDbVariable moRegistry;
    private DGridPaneForm moGridFamilies;

    /** Creates new form DFormVariable */
    public DFormVariable(DGuiClient client, String title) {
        setFormSettings(client, DGuiConsts.BEAN_FORM_EDIT, DModConsts.MU_VAR, DLibConsts.UNDEFINED, title);
        initComponents();
        initComponentsCustom();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jpContainer = new javax.swing.JPanel();
        jpVariable = new javax.swing.JPanel();
        jpVariable1 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jlCode = new javax.swing.JLabel();
        moTextCode = new sba.lib.gui.bean.DBeanFieldText();
        jPanel4 = new javax.swing.JPanel();
        jlName = new javax.swing.JLabel();
        moTextName = new sba.lib.gui.bean.DBeanFieldText();
        jPanel8 = new javax.swing.JPanel();
        jlUnit = new javax.swing.JLabel();
        moTextUnit = new sba.lib.gui.bean.DBeanFieldText();
        jpVariable2 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        jlDecimals = new javax.swing.JLabel();
        jsDecimals = new javax.swing.JSpinner();
        jPanel6 = new javax.swing.JPanel();
        jlValueMin = new javax.swing.JLabel();
        moDecValueMin = new sba.lib.gui.bean.DBeanFieldDecimal();
        jPanel7 = new javax.swing.JPanel();
        jlValueMax = new javax.swing.JLabel();
        moDecValueMax = new sba.lib.gui.bean.DBeanFieldDecimal();
        jpFamilies = new javax.swing.JPanel();

        jpContainer.setLayout(new java.awt.BorderLayout());

        jpVariable.setBorder(javax.swing.BorderFactory.createTitledBorder("Datos del registro:"));
        jpVariable.setLayout(new java.awt.GridLayout(1, 2));

        jpVariable1.setLayout(new java.awt.GridLayout(3, 1, 0, 5));

        jPanel3.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT, 5, 0));

        jlCode.setText("Código:*");
        jlCode.setPreferredSize(new java.awt.Dimension(100, 23));
        jPanel3.add(jlCode);

        moTextCode.setPreferredSize(new java.awt.Dimension(50, 23));
        jPanel3.add(moTextCode);

        jpVariable1.add(jPanel3);

        jPanel4.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT, 5, 0));

        jlName.setText("Nombre:*");
        jlName.setPreferredSize(new java.awt.Dimension(100, 23));
        jPanel4.add(jlName);

        moTextName.setPreferredSize(new java.awt.Dimension(200, 23));
        jPanel4.add(moTextName);

        jpVariable1.add(jPanel4);

        jPanel8.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT, 5, 0));

        jlUnit.setText("Unidad:");
        jlUnit.setPreferredSize(new java.awt.Dimension(100, 23));
        jPanel8.add(jlUnit);
        jPanel8.add(moTextUnit);

        jpVariable1.add(jPanel8);

        jpVariable.add(jpVariable1);

        jpVariable2.setLayout(new java.awt.GridLayout(3, 1, 0, 5));

        jPanel5.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT, 5, 0));

        jlDecimals.setText("Decimales:");
        jlDecimals.setPreferredSize(new java.awt.Dimension(100, 23));
        jPanel5.add(jlDecimals);

        jsDecimals.setModel(new javax.swing.SpinnerNumberModel(0, 0, 8, 1));
        jsDecimals.setPreferredSize(new java.awt.Dimension(50, 23));
        jPanel5.add(jsDecimals);

        jpVariable2.add(jPanel5);

        jPanel6.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT, 5, 0));

        jlValueMin.setText("Valor mínimo:");
        jlValueMin.setPreferredSize(new java.awt.Dimension(100, 23));
        jPanel6.add(jlValueMin);
        jPanel6.add(moDecValueMin);

        jpVariable2.add(jPanel6);

        jPanel7.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT, 5, 0));

        jlValueMax.setText("Valor máximo:");
        jlValueMax.setPreferredSize(new java.awt.Dimension(100, 23));
        jPanel7.add(jlValueMax);
        jPanel7.add(moDecValueMax);

        jpVariable2.add(jPanel7);

        jpVariable.add(jpVariable2);

        jpContainer.add(jpVariable, java.awt.BorderLayout.NORTH);

        jpFamilies.setBorder(javax.swing.BorderFactory.createTitledBorder("Familias:"));
        jpFamilies.setLayout(new java.awt.BorderLayout());
        jpContainer.add(jpFamilies, java.awt.BorderLayout.CENTER);

        getContentPane().add(jpContainer, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JLabel jlCode;
    private javax.swing.JLabel jlDecimals;
    private javax.swing.JLabel jlName;
    private javax.swing.JLabel jlUnit;
    private javax.swing.JLabel jlValueMax;
    private javax.swing.JLabel jlValueMin;
    private javax.swing.JPanel jpContainer;
    private javax.swing.JPanel jpFamilies;
    private javax.swing.JPanel jpVariable;
    private javax.swing.JPanel jpVariable1;
    private javax.swing.JPanel jpVariable2;
    private javax.swing.JSpinner jsDecimals;
    private sba.lib.gui.bean.DBeanFieldDecimal moDecValueMax;
    private sba.lib.gui.bean.DBeanFieldDecimal moDecValueMin;
    private sba.lib.gui.bean.DBeanFieldText moTextCode;
    private sba.lib.gui.bean.DBeanFieldText moTextName;
    private sba.lib.gui.bean.DBeanFieldText moTextUnit;
    // End of variables declaration//GEN-END:variables

    /*
     * Private methods
     */

    private void initComponentsCustom() {
        DGuiUtils.setWindowBounds(this, 640, 400);
        
        moTextCode.setTextSettings(DGuiUtils.getLabelName(jlCode), 5);
        moTextName.setTextSettings(DGuiUtils.getLabelName(jlName), 50);
        moTextUnit.setTextSettings(DGuiUtils.getLabelName(jlUnit), 10, 0);
        moDecValueMin.setDecimalSettings(DGuiUtils.getLabelName(jlValueMin), DGuiConsts.GUI_TYPE_DEC_AMT_UNIT, false);
        moDecValueMax.setDecimalSettings(DGuiUtils.getLabelName(jlValueMax), DGuiConsts.GUI_TYPE_DEC_AMT_UNIT, false);
        
        moFields.addField(moTextCode);
        moFields.addField(moTextName);
        moFields.addField(moTextUnit);
        moFields.addField(moDecValueMin);
        moFields.addField(moDecValueMax);
        
        moFields.setFormButton(jbSave);
        
        moGridFamilies = new DGridPaneForm(miClient, mnFormType, DModConsts.CU_FAM, DGuiUtils.getLabelName(((TitledBorder) jpFamilies.getBorder()).getTitle())) {
            
            @Override
            public void initGrid() {
                setRowButtonsEnabled(false);
            }
            
            @Override
            public void createGridColumns() {
                int col = 0;
                DGridColumnForm[] columns = new DGridColumnForm[3];

                columns[col++] = new DGridColumnForm(DGridConsts.COL_TYPE_TEXT_NAME_CAT_L, DGridConsts.COL_TITLE_NAME);
                columns[col++] = new DGridColumnForm(DGridConsts.COL_TYPE_TEXT_CODE_CAT, DGridConsts.COL_TITLE_CODE);
                columns[col] = new DGridColumnForm(DGridConsts.COL_TYPE_BOOL_M, "Aplica");
                columns[col].setEditable(true);

                for (col = 0; col < columns.length; col++) {
                    moModel.getGridColumns().add(columns[col]);
                }
            }
        };
        
        jpFamilies.add(moGridFamilies, BorderLayout.CENTER);
        mvFormGrids.add(moGridFamilies);
    }
    
    /*
     * Public methods
     */
    
    /*
     * Overriden methods
     */
    
    @Override
    public void addAllListeners() {
        jsDecimals.addChangeListener(this);
    }

    @Override
    public void removeAllListeners() {

    }

    @Override
    public void reloadCatalogues() {
        
    }

    @Override
    public void setRegistry(DDbRegistry registry) throws Exception {
        moRegistry = (DDbVariable) registry;

        mnFormResult = DLibConsts.UNDEFINED;
        mbFirstActivation = true;

        removeAllListeners();
        reloadCatalogues();

        if (moRegistry.isRegistryNew()) {
            moRegistry.setCode("");
            moRegistry.initPrimaryKey();
            jtfRegistryKey.setText("");
        }
        else {
            jtfRegistryKey.setText(DLibUtils.textKey(moRegistry.getPrimaryKey()));
        }

        moTextCode.setValue(moRegistry.getCode());
        moTextName.setValue(moRegistry.getName());
        moTextUnit.setValue(moRegistry.getUnit());
        jsDecimals.setValue(moRegistry.getDecimals());
        moDecValueMin.setValue(moRegistry.getValueMin());
        moDecValueMax.setValue(moRegistry.getValueMax());
        
        moKeyDepartment.setValue(new int[] { moRegistry.getFkDepartmentId() });
/*XXX        
        for (DDbFamily itemFamily : DMfgUtils.readItemFamilies(miClient.getSession(), DModSysConsts.CS_ITM_TP_PB)) {
            optionFamilies.add(new DRowOption(itemFamily.getPkItemFamilyId(), itemFamily.getCode(), itemFamily.getName(), false));
        }
*/
        for (DDbLinePrepItemFamily linePrepItemFamily : moRegistry.getChildItemFamilies()) {
            for (DGridRow row : optionFamilies) {
                if (((DRowOption) row).OptionId == linePrepItemFamily.getPkItemFamilyId()) {
                    ((DRowOption) row).Selected = true;
                    break;
                }
            }
        }
        
        moGridFamilies.populateGrid(optionFamilies);
        
        for (DDbLinePack linePack : DMfgUtils.readLinePacks(miClient.getSession())) {
            optionLinePacks.add(new DRowOption(linePack.getPkLinePackId(), linePack.getCode(), linePack.getName(), false));
        }

        for (DDbLinePrepLinePack linePrepLinePack : moRegistry.getChildLinePacks()) {
            for (DGridRow row : optionLinePacks) {
                if (((DRowOption) row).OptionId == linePrepLinePack.getPkLinePackId()) {
                    ((DRowOption) row).Selected = true;
                    break;
                }
            }
        }
        
        moGridLinePacks.populateGrid(optionLinePacks);
        
        setFormEditable(true);

        addAllListeners();
    }

    @Override
    public DDbLinePrep getRegistry() throws Exception {
        DDbLinePrepItemFamily linePrepItemFamily = null;
        DDbLinePrepLinePack linePrepLinePack = null;
        DDbLinePrep registry = moRegistry.clone();

        if (registry.isRegistryNew()) { }

        registry.setCode(moTextCode.getValue());
        registry.setName(moTextName.getValue());
        registry.setFkDepartmentId(moKeyDepartment.getValue()[0]);
        
        registry.getChildItemFamilies().clear();
        for (DGridRow row : moGridFamilies.getModel().getGridRows()) {
            if (((DRowOption) row).Selected) {
                linePrepItemFamily = new DDbLinePrepItemFamily();
                
                //linePrepItemFamily.setPkLinePrepId(...);
                linePrepItemFamily.setPkItemFamilyId(((DRowOption) row).OptionId);
                
                registry.getChildItemFamilies().add(linePrepItemFamily);
            }
        }
        
        registry.getChildLinePacks().clear();
        for (DGridRow row : moGridLinePacks.getModel().getGridRows()) {
            if (((DRowOption) row).Selected) {
                linePrepLinePack = new DDbLinePrepLinePack();
                
                //linePrepLinePack.setPkLinePrepId(...);
                linePrepLinePack.setPkLinePackId(((DRowOption) row).OptionId);
                
                registry.getChildLinePacks().add(linePrepLinePack);
            }
        }

        return registry;
    }

    @Override
    public DGuiValidation validateForm() {
        return moFields.validateFields();
    }

    @Override
    public void stateChanged(ChangeEvent e) {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }
}
