/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

package ft.mod.mfg.form;

import ft.mod.DModConsts;
import ft.mod.DModSysConsts;
import ft.mod.cfg.db.DCfgUtils;
import ft.mod.cfg.db.DDbItem;
import ft.mod.mfg.db.DDbFormula;
import ft.mod.mfg.db.DDbFormulaComp;
import ft.mod.mfg.db.DDbJob;
import ft.mod.mfg.db.DDbJobConsump;
import ft.mod.mfg.db.DDbJobMfgProd;
import ft.mod.mfg.db.DDbJobReqment;
import ft.mod.mfg.db.DDbJobVariable;
import ft.mod.mfg.db.DDbVariable;
import ft.mod.mfg.db.DMfgUtils;
import ft.mod.qty.db.DDbTest;
import ft.mod.qty.db.DDbTestApp;
import ft.mod.qty.db.DDbTestAppResult;
import ft.mod.qty.db.DDbTestVariable;
import java.awt.BorderLayout;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.event.FocusEvent;
import java.awt.event.FocusListener;
import java.awt.event.ItemEvent;
import java.awt.event.ItemListener;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.Vector;
import javax.swing.JButton;
import javax.swing.ListSelectionModel;
import javax.swing.event.ListSelectionEvent;
import javax.swing.event.ListSelectionListener;
import sba.lib.DLibConsts;
import sba.lib.DLibUtils;
import sba.lib.db.DDbRegistry;
import sba.lib.grid.DGridColumnForm;
import sba.lib.grid.DGridConsts;
import sba.lib.grid.DGridPaneForm;
import sba.lib.grid.DGridPaneFormOwner;
import sba.lib.grid.DGridRow;
import sba.lib.grid.cell.DGridCellRendererNumberVariable;
import sba.lib.gui.DGuiClient;
import sba.lib.gui.DGuiConsts;
import sba.lib.gui.DGuiFieldKeyGroup;
import sba.lib.gui.DGuiFields;
import sba.lib.gui.DGuiParams;
import sba.lib.gui.DGuiUtils;
import sba.lib.gui.DGuiValidation;
import sba.lib.gui.bean.DBeanFieldDecimal;
import sba.lib.gui.bean.DBeanFieldKey;
import sba.lib.gui.bean.DBeanForm;

/**
 *
 * @author Sergio Flores
 */
public class DFormJob extends DBeanForm implements DGridPaneFormOwner, ActionListener, ItemListener, FocusListener, ListSelectionListener {
    
    private static final int TAB_MFG = 1;
    private static final int TAB_QTY = 2;
    private static final int TAB_STS = 3;

    private DDbJob moRegistry;
    private DDbFormula moFormula;
    private DDbItem moItemConsump;
    private DDbItem moItemMfgProd;
    private DDbTest moTest;
    private int mnJobStatus;
    private String msCompTypeNameItm;
    private String msCompTypeNameFam;
    private HashMap<Integer, String> moMapStatus;
    private ArrayList<DDbJobConsump> maConsumps;
    private ArrayList<DDbTestApp> maTestApps;
    private DGuiFields moFieldsConsump;
    private DGuiFields moFieldsMfgProd;
    private DGuiFields moFieldsTestApp;
    private DGridPaneForm moGridReqments;
    private DGridPaneForm moGridConsumps;
    private DGridPaneForm moGridMfgProds;
    private DGridPaneForm moGridVariables;
    private DGridPaneForm moGridTestApps;
    private DGridPaneForm moGridTestAppsResults;
    private DGuiFieldKeyGroup moKeyGroupJobFormula;
    private DGuiFieldKeyGroup moKeyGroupJobLine;
    private DGuiFieldKeyGroup moKeyGroupConsumpItem;
    private DGuiFieldKeyGroup moKeyGroupMfgProdItem;

    /** Creates new form DFormJob */
    public DFormJob(DGuiClient client, String title) {
        setFormSettings(client, DGuiConsts.BEAN_FORM_EDIT, DModConsts.M_JOB, DLibConsts.UNDEFINED, title);
        initComponents();
        initComponentsCustom();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jpContainer = new javax.swing.JPanel();
        jpJob = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jPanel17 = new javax.swing.JPanel();
        jlJobNumber = new javax.swing.JLabel();
        jtfJobSeries = new javax.swing.JTextField();
        jtfJobNumber = new javax.swing.JTextField();
        jPanel5 = new javax.swing.JPanel();
        jlJobDate = new javax.swing.JLabel();
        moDateJobDate = new sba.lib.gui.bean.DBeanFieldDate();
        jPanel6 = new javax.swing.JPanel();
        jlJobItemType = new javax.swing.JLabel();
        moKeyJobItemType = new sba.lib.gui.bean.DBeanFieldKey();
        jPanel11 = new javax.swing.JPanel();
        jlJobFamily = new javax.swing.JLabel();
        moKeyJobFamily = new sba.lib.gui.bean.DBeanFieldKey();
        jPanel22 = new javax.swing.JPanel();
        jlJobItem = new javax.swing.JLabel();
        moKeyJobItem = new sba.lib.gui.bean.DBeanFieldKey();
        jPanel18 = new javax.swing.JPanel();
        jlJobFormula = new javax.swing.JLabel();
        moKeyJobFormula = new sba.lib.gui.bean.DBeanFieldKey();
        jPanel20 = new javax.swing.JPanel();
        jlJobFormulaQuantity = new javax.swing.JLabel();
        moCompJobFormulaQuantity = new sba.lib.gui.bean.DBeanCompoundField();
        moCompJobFormulaMass = new sba.lib.gui.bean.DBeanCompoundField();
        jPanel19 = new javax.swing.JPanel();
        jlJobLoads = new javax.swing.JLabel();
        moDecJobLoads = new sba.lib.gui.bean.DBeanFieldDecimal();
        jPanel21 = new javax.swing.JPanel();
        jlJobJobQuantity = new javax.swing.JLabel();
        moCompJobJobQuantity = new sba.lib.gui.bean.DBeanCompoundField();
        jPanel29 = new javax.swing.JPanel();
        jlJobMfgProdQuantity = new javax.swing.JLabel();
        moCompJobMfgProdQuantity = new sba.lib.gui.bean.DBeanCompoundField();
        jPanel9 = new javax.swing.JPanel();
        jPanel23 = new javax.swing.JPanel();
        jlJobDepart = new javax.swing.JLabel();
        moKeyJobDepart = new sba.lib.gui.bean.DBeanFieldKey();
        jPanel24 = new javax.swing.JPanel();
        jlJobLine = new javax.swing.JLabel();
        moKeyJobLine = new sba.lib.gui.bean.DBeanFieldKey();
        jPanel14 = new javax.swing.JPanel();
        jlJobStatus = new javax.swing.JLabel();
        jtfJobStatus = new javax.swing.JTextField();
        jbJobGoStatusPrev = new javax.swing.JButton();
        jbJobGoStatusNext = new javax.swing.JButton();
        jPanel13 = new javax.swing.JPanel();
        jlJobLot = new javax.swing.JLabel();
        moTextJobLot = new sba.lib.gui.bean.DBeanFieldText();
        jbJobGenerateLot = new javax.swing.JButton();
        jPanel15 = new javax.swing.JPanel();
        jlJobTimeStart = new javax.swing.JLabel();
        moTimeJobTimeStart = new sba.lib.gui.bean.DBeanFieldDatetime();
        jPanel16 = new javax.swing.JPanel();
        jlJobTimeEnd = new javax.swing.JLabel();
        moTimeJobTimeEnd = new sba.lib.gui.bean.DBeanFieldDatetime();
        jPanel25 = new javax.swing.JPanel();
        jlJobPackingFactor = new javax.swing.JLabel();
        moDecJobPackingFactor = new sba.lib.gui.bean.DBeanFieldDecimal();
        jPanel27 = new javax.swing.JPanel();
        jlJobReqmentMass = new javax.swing.JLabel();
        moCompJobReqmentMass = new sba.lib.gui.bean.DBeanCompoundField();
        jPanel26 = new javax.swing.JPanel();
        jlJobConsumpMass = new javax.swing.JLabel();
        moCompJobConsumpMass = new sba.lib.gui.bean.DBeanCompoundField();
        jPanel33 = new javax.swing.JPanel();
        jlJobMfgProdMass = new javax.swing.JLabel();
        moCompJobMfgProdMass = new sba.lib.gui.bean.DBeanCompoundField();
        jtpJob = new javax.swing.JTabbedPane();
        jpMfg = new javax.swing.JPanel();
        jpReqment = new javax.swing.JPanel();
        jpConsump = new javax.swing.JPanel();
        jpConsumpData = new javax.swing.JPanel();
        jPanel10 = new javax.swing.JPanel();
        jlConsumpItemType = new javax.swing.JLabel();
        moKeyConsumpItemType = new sba.lib.gui.bean.DBeanFieldKey();
        jtfConsumpType = new javax.swing.JTextField();
        jPanel7 = new javax.swing.JPanel();
        jlConsumpItem = new javax.swing.JLabel();
        moKeyConsumpItem = new sba.lib.gui.bean.DBeanFieldKey();
        jtfConsumpItem = new javax.swing.JTextField();
        jPanel8 = new javax.swing.JPanel();
        jlConsumpQuantity = new javax.swing.JLabel();
        moCompConsumpQuantity = new sba.lib.gui.bean.DBeanCompoundField();
        moCompConsumpMass = new sba.lib.gui.bean.DBeanCompoundField();
        jPanel12 = new javax.swing.JPanel();
        jlConsumpLot = new javax.swing.JLabel();
        moTextConsumpLot = new sba.lib.gui.bean.DBeanFieldText();
        moBoolConsumpRework = new sba.lib.gui.bean.DBeanFieldBoolean();
        jbConsumpNew = new javax.swing.JButton();
        jbConsumpAdd = new javax.swing.JButton();
        jbConsumpClear = new javax.swing.JButton();
        jpMfgProd = new javax.swing.JPanel();
        jpMfgProdData = new javax.swing.JPanel();
        jPanel28 = new javax.swing.JPanel();
        jlMfgProdItemType = new javax.swing.JLabel();
        moKeyMfgProdItemType = new sba.lib.gui.bean.DBeanFieldKey();
        jPanel31 = new javax.swing.JPanel();
        jlMfgProdItem = new javax.swing.JLabel();
        moKeyMfgProdItem = new sba.lib.gui.bean.DBeanFieldKey();
        jPanel30 = new javax.swing.JPanel();
        jlMfgProdQuantity = new javax.swing.JLabel();
        moCompMfgProdQuantity = new sba.lib.gui.bean.DBeanCompoundField();
        moCompMfgProdMass = new sba.lib.gui.bean.DBeanCompoundField();
        jPanel32 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jbMfgProdNew = new javax.swing.JButton();
        jbMfgProdAdd = new javax.swing.JButton();
        jbMfgProdClear = new javax.swing.JButton();
        jpQty = new javax.swing.JPanel();
        jpVariables = new javax.swing.JPanel();
        jPanel36 = new javax.swing.JPanel();
        jbVariablesClear = new javax.swing.JButton();
        jpTestApps = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jlTest = new javax.swing.JLabel();
        moKeyTest = new sba.lib.gui.bean.DBeanFieldKey();
        jPanel34 = new javax.swing.JPanel();
        jlTestAppDate = new javax.swing.JLabel();
        moDateTestAppDate = new sba.lib.gui.bean.DBeanFieldDate();
        jtfTestApp = new javax.swing.JTextField();
        jbTestAppAdd = new javax.swing.JButton();
        jbTestAppClear = new javax.swing.JButton();
        jpTestAppsResults = new javax.swing.JPanel();
        jPanel35 = new javax.swing.JPanel();
        jlTestAppResults = new javax.swing.JLabel();
        jtfTestAppResults = new javax.swing.JTextField();
        jbTestAppResultsDelete = new javax.swing.JButton();
        jpSts = new javax.swing.JPanel();

        jpContainer.setLayout(new java.awt.BorderLayout());

        jpJob.setBorder(javax.swing.BorderFactory.createTitledBorder("Datos del registro:"));
        jpJob.setLayout(new java.awt.GridLayout(1, 3));

        jPanel1.setLayout(new java.awt.GridLayout(10, 1, 0, 5));

        jPanel17.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT, 5, 0));

        jlJobNumber.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jlJobNumber.setText("Folio:");
        jlJobNumber.setPreferredSize(new java.awt.Dimension(100, 23));
        jPanel17.add(jlJobNumber);

        jtfJobSeries.setEditable(false);
        jtfJobSeries.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jtfJobSeries.setText("S");
        jtfJobSeries.setFocusable(false);
        jtfJobSeries.setPreferredSize(new java.awt.Dimension(35, 23));
        jPanel17.add(jtfJobSeries);

        jtfJobNumber.setEditable(false);
        jtfJobNumber.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jtfJobNumber.setHorizontalAlignment(javax.swing.JTextField.TRAILING);
        jtfJobNumber.setText("0");
        jtfJobNumber.setFocusable(false);
        jtfJobNumber.setPreferredSize(new java.awt.Dimension(75, 23));
        jPanel17.add(jtfJobNumber);

        jPanel1.add(jPanel17);

        jPanel5.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT, 5, 0));

        jlJobDate.setText("Fecha:*");
        jlJobDate.setPreferredSize(new java.awt.Dimension(100, 23));
        jPanel5.add(jlJobDate);
        jPanel5.add(moDateJobDate);

        jPanel1.add(jPanel5);

        jPanel6.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT, 5, 0));

        jlJobItemType.setText("Tipo producto:*");
        jlJobItemType.setPreferredSize(new java.awt.Dimension(100, 23));
        jPanel6.add(jlJobItemType);

        moKeyJobItemType.setPreferredSize(new java.awt.Dimension(200, 23));
        jPanel6.add(moKeyJobItemType);

        jPanel1.add(jPanel6);

        jPanel11.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT, 5, 0));

        jlJobFamily.setText("Familia:*");
        jlJobFamily.setPreferredSize(new java.awt.Dimension(100, 23));
        jPanel11.add(jlJobFamily);

        moKeyJobFamily.setPreferredSize(new java.awt.Dimension(200, 23));
        jPanel11.add(moKeyJobFamily);

        jPanel1.add(jPanel11);

        jPanel22.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT, 5, 0));

        jlJobItem.setText("Producto:*");
        jlJobItem.setPreferredSize(new java.awt.Dimension(100, 23));
        jPanel22.add(jlJobItem);

        moKeyJobItem.setPreferredSize(new java.awt.Dimension(300, 23));
        jPanel22.add(moKeyJobItem);

        jPanel1.add(jPanel22);

        jPanel18.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT, 5, 0));

        jlJobFormula.setText("Fórmula:*");
        jlJobFormula.setPreferredSize(new java.awt.Dimension(100, 23));
        jPanel18.add(jlJobFormula);

        moKeyJobFormula.setPreferredSize(new java.awt.Dimension(300, 23));
        jPanel18.add(moKeyJobFormula);

        jPanel1.add(jPanel18);

        jPanel20.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT, 5, 0));

        jlJobFormulaQuantity.setText("Cant. fórmula:");
        jlJobFormulaQuantity.setPreferredSize(new java.awt.Dimension(100, 23));
        jPanel20.add(jlJobFormulaQuantity);

        moCompJobFormulaQuantity.setToolTipText("Cant. fórmula");
        jPanel20.add(moCompJobFormulaQuantity);

        moCompJobFormulaMass.setToolTipText("Masa fórmula");
        jPanel20.add(moCompJobFormulaMass);

        jPanel1.add(jPanel20);

        jPanel19.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT, 5, 0));

        jlJobLoads.setText("Cargas:");
        jlJobLoads.setPreferredSize(new java.awt.Dimension(100, 23));
        jPanel19.add(jlJobLoads);
        jPanel19.add(moDecJobLoads);

        jPanel1.add(jPanel19);

        jPanel21.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT, 5, 0));

        jlJobJobQuantity.setText("Cant. orden:");
        jlJobJobQuantity.setPreferredSize(new java.awt.Dimension(100, 23));
        jPanel21.add(jlJobJobQuantity);
        jPanel21.add(moCompJobJobQuantity);

        jPanel1.add(jPanel21);

        jPanel29.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT, 5, 0));

        jlJobMfgProdQuantity.setText("Cant. produccón:");
        jlJobMfgProdQuantity.setPreferredSize(new java.awt.Dimension(100, 23));
        jPanel29.add(jlJobMfgProdQuantity);
        jPanel29.add(moCompJobMfgProdQuantity);

        jPanel1.add(jPanel29);

        jpJob.add(jPanel1);

        jPanel9.setLayout(new java.awt.GridLayout(10, 1, 0, 5));

        jPanel23.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT, 5, 0));

        jlJobDepart.setText("Depto. producción:*");
        jlJobDepart.setPreferredSize(new java.awt.Dimension(100, 23));
        jPanel23.add(jlJobDepart);

        moKeyJobDepart.setPreferredSize(new java.awt.Dimension(200, 23));
        jPanel23.add(moKeyJobDepart);

        jPanel9.add(jPanel23);

        jPanel24.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT, 5, 0));

        jlJobLine.setText("Línea producción:*");
        jlJobLine.setPreferredSize(new java.awt.Dimension(100, 23));
        jPanel24.add(jlJobLine);

        moKeyJobLine.setPreferredSize(new java.awt.Dimension(200, 23));
        jPanel24.add(moKeyJobLine);

        jPanel9.add(jPanel24);

        jPanel14.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT, 5, 0));

        jlJobStatus.setText("Estatus orden:*");
        jlJobStatus.setPreferredSize(new java.awt.Dimension(100, 23));
        jPanel14.add(jlJobStatus);

        jtfJobStatus.setEditable(false);
        jtfJobStatus.setFocusable(false);
        jtfJobStatus.setPreferredSize(new java.awt.Dimension(150, 23));
        jPanel14.add(jtfJobStatus);

        jbJobGoStatusPrev.setText("<<<");
        jbJobGoStatusPrev.setToolTipText("Ir a estatus previo");
        jbJobGoStatusPrev.setMargin(new java.awt.Insets(0, 0, 0, 0));
        jbJobGoStatusPrev.setPreferredSize(new java.awt.Dimension(50, 23));
        jPanel14.add(jbJobGoStatusPrev);

        jbJobGoStatusNext.setText(">>>");
        jbJobGoStatusNext.setToolTipText("Ir a estatus siguiente");
        jbJobGoStatusNext.setMargin(new java.awt.Insets(0, 0, 0, 0));
        jbJobGoStatusNext.setPreferredSize(new java.awt.Dimension(50, 23));
        jPanel14.add(jbJobGoStatusNext);

        jPanel9.add(jPanel14);

        jPanel13.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT, 5, 0));

        jlJobLot.setText("Lote:*");
        jlJobLot.setPreferredSize(new java.awt.Dimension(100, 23));
        jPanel13.add(jlJobLot);

        moTextJobLot.setPreferredSize(new java.awt.Dimension(150, 23));
        jPanel13.add(moTextJobLot);

        jbJobGenerateLot.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sba/lib/img/cmd_std_act.gif"))); // NOI18N
        jbJobGenerateLot.setToolTipText("Generar");
        jbJobGenerateLot.setPreferredSize(new java.awt.Dimension(23, 23));
        jPanel13.add(jbJobGenerateLot);

        jPanel9.add(jPanel13);

        jPanel15.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT, 5, 0));

        jlJobTimeStart.setText("Fecha-hora inicial:");
        jlJobTimeStart.setPreferredSize(new java.awt.Dimension(100, 23));
        jPanel15.add(jlJobTimeStart);
        jPanel15.add(moTimeJobTimeStart);

        jPanel9.add(jPanel15);

        jPanel16.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT, 5, 0));

        jlJobTimeEnd.setText("Fecha-hora final:");
        jlJobTimeEnd.setPreferredSize(new java.awt.Dimension(100, 23));
        jPanel16.add(jlJobTimeEnd);
        jPanel16.add(moTimeJobTimeEnd);

        jPanel9.add(jPanel16);

        jPanel25.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT, 5, 0));

        jlJobPackingFactor.setText("Factor empaque:");
        jlJobPackingFactor.setPreferredSize(new java.awt.Dimension(100, 23));
        jPanel25.add(jlJobPackingFactor);
        jPanel25.add(moDecJobPackingFactor);

        jPanel9.add(jPanel25);

        jPanel27.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT, 5, 0));

        jlJobReqmentMass.setText("Masa requerida:");
        jlJobReqmentMass.setPreferredSize(new java.awt.Dimension(100, 23));
        jPanel27.add(jlJobReqmentMass);
        jPanel27.add(moCompJobReqmentMass);

        jPanel9.add(jPanel27);

        jPanel26.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT, 5, 0));

        jlJobConsumpMass.setText("Masa consumida:");
        jlJobConsumpMass.setPreferredSize(new java.awt.Dimension(100, 23));
        jPanel26.add(jlJobConsumpMass);
        jPanel26.add(moCompJobConsumpMass);

        jPanel9.add(jPanel26);

        jPanel33.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT, 5, 0));

        jlJobMfgProdMass.setText("Masa producción:");
        jlJobMfgProdMass.setPreferredSize(new java.awt.Dimension(100, 23));
        jPanel33.add(jlJobMfgProdMass);
        jPanel33.add(moCompJobMfgProdMass);

        jPanel9.add(jPanel33);

        jpJob.add(jPanel9);

        jpContainer.add(jpJob, java.awt.BorderLayout.NORTH);

        jpMfg.setLayout(new java.awt.GridLayout(1, 3));

        jpReqment.setBorder(javax.swing.BorderFactory.createTitledBorder("Insumos requeridos:"));
        jpReqment.setLayout(new java.awt.BorderLayout());
        jpMfg.add(jpReqment);

        jpConsump.setBorder(javax.swing.BorderFactory.createTitledBorder("Insumos consumidos:"));
        jpConsump.setLayout(new java.awt.BorderLayout(0, 5));

        jpConsumpData.setLayout(new java.awt.GridLayout(4, 0, 0, 5));

        jPanel10.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT, 5, 0));

        jlConsumpItemType.setText("Tipo:*");
        jlConsumpItemType.setPreferredSize(new java.awt.Dimension(75, 23));
        jPanel10.add(jlConsumpItemType);

        moKeyConsumpItemType.setPreferredSize(new java.awt.Dimension(240, 23));
        jPanel10.add(moKeyConsumpItemType);

        jtfConsumpType.setEditable(false);
        jtfConsumpType.setText("jTextField2");
        jtfConsumpType.setFocusable(false);
        jtfConsumpType.setPreferredSize(new java.awt.Dimension(240, 23));
        jPanel10.add(jtfConsumpType);

        jpConsumpData.add(jPanel10);

        jPanel7.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT, 5, 0));

        jlConsumpItem.setText("Insumo:*");
        jlConsumpItem.setPreferredSize(new java.awt.Dimension(75, 23));
        jPanel7.add(jlConsumpItem);

        moKeyConsumpItem.setPreferredSize(new java.awt.Dimension(240, 23));
        jPanel7.add(moKeyConsumpItem);

        jtfConsumpItem.setEditable(false);
        jtfConsumpItem.setText("jTextField2");
        jtfConsumpItem.setFocusable(false);
        jtfConsumpItem.setPreferredSize(new java.awt.Dimension(240, 23));
        jPanel7.add(jtfConsumpItem);

        jpConsumpData.add(jPanel7);

        jPanel8.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT, 5, 0));

        jlConsumpQuantity.setText("Cantidad:*");
        jlConsumpQuantity.setPreferredSize(new java.awt.Dimension(75, 23));
        jPanel8.add(jlConsumpQuantity);

        moCompConsumpQuantity.setPreferredSize(new java.awt.Dimension(125, 23));
        jPanel8.add(moCompConsumpQuantity);

        moCompConsumpMass.setToolTipText("Masa");
        moCompConsumpMass.setPreferredSize(new java.awt.Dimension(110, 23));
        jPanel8.add(moCompConsumpMass);

        jpConsumpData.add(jPanel8);

        jPanel12.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT, 5, 0));

        jlConsumpLot.setText("Lote:*");
        jlConsumpLot.setPreferredSize(new java.awt.Dimension(75, 23));
        jPanel12.add(jlConsumpLot);

        moTextConsumpLot.setPreferredSize(new java.awt.Dimension(85, 23));
        jPanel12.add(moTextConsumpLot);

        moBoolConsumpRework.setText("Re-trab.");
        moBoolConsumpRework.setPreferredSize(new java.awt.Dimension(70, 23));
        jPanel12.add(moBoolConsumpRework);

        jbConsumpNew.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sba/lib/img/cmd_std_new.gif"))); // NOI18N
        jbConsumpNew.setToolTipText("Nuevo");
        jbConsumpNew.setPreferredSize(new java.awt.Dimension(23, 23));
        jPanel12.add(jbConsumpNew);

        jbConsumpAdd.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sba/lib/img/cmd_std_add.gif"))); // NOI18N
        jbConsumpAdd.setToolTipText("Agregar");
        jbConsumpAdd.setPreferredSize(new java.awt.Dimension(23, 23));
        jPanel12.add(jbConsumpAdd);

        jbConsumpClear.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sba/lib/img/cmd_std_clear.gif"))); // NOI18N
        jbConsumpClear.setToolTipText("Limpiar");
        jbConsumpClear.setPreferredSize(new java.awt.Dimension(23, 23));
        jPanel12.add(jbConsumpClear);

        jpConsumpData.add(jPanel12);

        jpConsump.add(jpConsumpData, java.awt.BorderLayout.NORTH);

        jpMfg.add(jpConsump);

        jpMfgProd.setBorder(javax.swing.BorderFactory.createTitledBorder("Producción:"));
        jpMfgProd.setLayout(new java.awt.BorderLayout(0, 5));

        jpMfgProdData.setLayout(new java.awt.GridLayout(4, 0, 0, 5));

        jPanel28.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT, 5, 0));

        jlMfgProdItemType.setText("Tipo:*");
        jlMfgProdItemType.setPreferredSize(new java.awt.Dimension(75, 23));
        jPanel28.add(jlMfgProdItemType);

        moKeyMfgProdItemType.setPreferredSize(new java.awt.Dimension(240, 23));
        jPanel28.add(moKeyMfgProdItemType);

        jpMfgProdData.add(jPanel28);

        jPanel31.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT, 5, 0));

        jlMfgProdItem.setText("Producto:*");
        jlMfgProdItem.setPreferredSize(new java.awt.Dimension(75, 23));
        jPanel31.add(jlMfgProdItem);

        moKeyMfgProdItem.setPreferredSize(new java.awt.Dimension(240, 23));
        jPanel31.add(moKeyMfgProdItem);

        jpMfgProdData.add(jPanel31);

        jPanel30.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT, 5, 0));

        jlMfgProdQuantity.setText("Cantidad:*");
        jlMfgProdQuantity.setPreferredSize(new java.awt.Dimension(75, 23));
        jPanel30.add(jlMfgProdQuantity);

        moCompMfgProdQuantity.setPreferredSize(new java.awt.Dimension(125, 23));
        jPanel30.add(moCompMfgProdQuantity);

        moCompMfgProdMass.setToolTipText("Masa");
        moCompMfgProdMass.setPreferredSize(new java.awt.Dimension(110, 23));
        jPanel30.add(moCompMfgProdMass);

        jpMfgProdData.add(jPanel30);

        jPanel32.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT, 5, 0));

        jLabel2.setPreferredSize(new java.awt.Dimension(240, 23));
        jPanel32.add(jLabel2);

        jbMfgProdNew.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sba/lib/img/cmd_std_new.gif"))); // NOI18N
        jbMfgProdNew.setToolTipText("Nuevo");
        jbMfgProdNew.setPreferredSize(new java.awt.Dimension(23, 23));
        jPanel32.add(jbMfgProdNew);

        jbMfgProdAdd.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sba/lib/img/cmd_std_add.gif"))); // NOI18N
        jbMfgProdAdd.setToolTipText("Agregar");
        jbMfgProdAdd.setPreferredSize(new java.awt.Dimension(23, 23));
        jPanel32.add(jbMfgProdAdd);

        jbMfgProdClear.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sba/lib/img/cmd_std_clear.gif"))); // NOI18N
        jbMfgProdClear.setToolTipText("Limpiar");
        jbMfgProdClear.setPreferredSize(new java.awt.Dimension(23, 23));
        jPanel32.add(jbMfgProdClear);

        jpMfgProdData.add(jPanel32);

        jpMfgProd.add(jpMfgProdData, java.awt.BorderLayout.NORTH);

        jpMfg.add(jpMfgProd);

        jtpJob.addTab("Producción", jpMfg);

        jpQty.setLayout(new java.awt.GridLayout(1, 3));

        jpVariables.setBorder(javax.swing.BorderFactory.createTitledBorder("Variables de producción:"));
        jpVariables.setLayout(new java.awt.BorderLayout(0, 5));

        jPanel36.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT, 5, 0));

        jbVariablesClear.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sba/lib/img/cmd_std_clear.gif"))); // NOI18N
        jbVariablesClear.setToolTipText("Limpiar");
        jbVariablesClear.setPreferredSize(new java.awt.Dimension(23, 23));
        jPanel36.add(jbVariablesClear);

        jpVariables.add(jPanel36, java.awt.BorderLayout.NORTH);

        jpQty.add(jpVariables);

        jpTestApps.setBorder(javax.swing.BorderFactory.createTitledBorder("Tests de calidad:"));
        jpTestApps.setLayout(new java.awt.BorderLayout(0, 5));

        jPanel2.setLayout(new java.awt.GridLayout(2, 1, 0, 5));

        jPanel3.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT, 5, 0));

        jlTest.setText("Test:*");
        jlTest.setPreferredSize(new java.awt.Dimension(75, 23));
        jPanel3.add(jlTest);

        moKeyTest.setPreferredSize(new java.awt.Dimension(200, 23));
        jPanel3.add(moKeyTest);

        jPanel2.add(jPanel3);

        jPanel34.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT, 5, 0));

        jlTestAppDate.setText("Fecha:*");
        jlTestAppDate.setPreferredSize(new java.awt.Dimension(75, 23));
        jPanel34.add(jlTestAppDate);
        jPanel34.add(moDateTestAppDate);

        jtfTestApp.setEditable(false);
        jtfTestApp.setFocusable(false);
        jtfTestApp.setPreferredSize(new java.awt.Dimension(75, 23));
        jPanel34.add(jtfTestApp);

        jbTestAppAdd.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sba/lib/img/cmd_std_add.gif"))); // NOI18N
        jbTestAppAdd.setToolTipText("Agregar");
        jbTestAppAdd.setPreferredSize(new java.awt.Dimension(23, 23));
        jPanel34.add(jbTestAppAdd);

        jbTestAppClear.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sba/lib/img/cmd_std_clear.gif"))); // NOI18N
        jbTestAppClear.setToolTipText("Limpiar");
        jbTestAppClear.setPreferredSize(new java.awt.Dimension(23, 23));
        jPanel34.add(jbTestAppClear);

        jPanel2.add(jPanel34);

        jpTestApps.add(jPanel2, java.awt.BorderLayout.NORTH);

        jpQty.add(jpTestApps);

        jpTestAppsResults.setBorder(javax.swing.BorderFactory.createTitledBorder("Resultados de tests de calidad:"));
        jpTestAppsResults.setLayout(new java.awt.BorderLayout(0, 5));

        jPanel35.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT, 5, 0));

        jlTestAppResults.setText("Resultados:");
        jlTestAppResults.setPreferredSize(new java.awt.Dimension(75, 23));
        jPanel35.add(jlTestAppResults);

        jtfTestAppResults.setEditable(false);
        jtfTestAppResults.setFocusable(false);
        jtfTestAppResults.setPreferredSize(new java.awt.Dimension(75, 23));
        jPanel35.add(jtfTestAppResults);

        jbTestAppResultsDelete.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sba/lib/img/cmd_std_delete.gif"))); // NOI18N
        jbTestAppResultsDelete.setToolTipText("Eliminar");
        jbTestAppResultsDelete.setPreferredSize(new java.awt.Dimension(23, 23));
        jPanel35.add(jbTestAppResultsDelete);

        jpTestAppsResults.add(jPanel35, java.awt.BorderLayout.NORTH);

        jpQty.add(jpTestAppsResults);

        jtpJob.addTab("Calidad", jpQty);
        jtpJob.addTab("Estadísticas", jpSts);

        jpContainer.add(jtpJob, java.awt.BorderLayout.CENTER);

        getContentPane().add(jpContainer, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel13;
    private javax.swing.JPanel jPanel14;
    private javax.swing.JPanel jPanel15;
    private javax.swing.JPanel jPanel16;
    private javax.swing.JPanel jPanel17;
    private javax.swing.JPanel jPanel18;
    private javax.swing.JPanel jPanel19;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel20;
    private javax.swing.JPanel jPanel21;
    private javax.swing.JPanel jPanel22;
    private javax.swing.JPanel jPanel23;
    private javax.swing.JPanel jPanel24;
    private javax.swing.JPanel jPanel25;
    private javax.swing.JPanel jPanel26;
    private javax.swing.JPanel jPanel27;
    private javax.swing.JPanel jPanel28;
    private javax.swing.JPanel jPanel29;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel30;
    private javax.swing.JPanel jPanel31;
    private javax.swing.JPanel jPanel32;
    private javax.swing.JPanel jPanel33;
    private javax.swing.JPanel jPanel34;
    private javax.swing.JPanel jPanel35;
    private javax.swing.JPanel jPanel36;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JButton jbConsumpAdd;
    private javax.swing.JButton jbConsumpClear;
    private javax.swing.JButton jbConsumpNew;
    private javax.swing.JButton jbJobGenerateLot;
    private javax.swing.JButton jbJobGoStatusNext;
    private javax.swing.JButton jbJobGoStatusPrev;
    private javax.swing.JButton jbMfgProdAdd;
    private javax.swing.JButton jbMfgProdClear;
    private javax.swing.JButton jbMfgProdNew;
    private javax.swing.JButton jbTestAppAdd;
    private javax.swing.JButton jbTestAppClear;
    private javax.swing.JButton jbTestAppResultsDelete;
    private javax.swing.JButton jbVariablesClear;
    private javax.swing.JLabel jlConsumpItem;
    private javax.swing.JLabel jlConsumpItemType;
    private javax.swing.JLabel jlConsumpLot;
    private javax.swing.JLabel jlConsumpQuantity;
    private javax.swing.JLabel jlJobConsumpMass;
    private javax.swing.JLabel jlJobDate;
    private javax.swing.JLabel jlJobDepart;
    private javax.swing.JLabel jlJobFamily;
    private javax.swing.JLabel jlJobFormula;
    private javax.swing.JLabel jlJobFormulaQuantity;
    private javax.swing.JLabel jlJobItem;
    private javax.swing.JLabel jlJobItemType;
    private javax.swing.JLabel jlJobJobQuantity;
    private javax.swing.JLabel jlJobLine;
    private javax.swing.JLabel jlJobLoads;
    private javax.swing.JLabel jlJobLot;
    private javax.swing.JLabel jlJobMfgProdMass;
    private javax.swing.JLabel jlJobMfgProdQuantity;
    private javax.swing.JLabel jlJobNumber;
    private javax.swing.JLabel jlJobPackingFactor;
    private javax.swing.JLabel jlJobReqmentMass;
    private javax.swing.JLabel jlJobStatus;
    private javax.swing.JLabel jlJobTimeEnd;
    private javax.swing.JLabel jlJobTimeStart;
    private javax.swing.JLabel jlMfgProdItem;
    private javax.swing.JLabel jlMfgProdItemType;
    private javax.swing.JLabel jlMfgProdQuantity;
    private javax.swing.JLabel jlTest;
    private javax.swing.JLabel jlTestAppDate;
    private javax.swing.JLabel jlTestAppResults;
    private javax.swing.JPanel jpConsump;
    private javax.swing.JPanel jpConsumpData;
    private javax.swing.JPanel jpContainer;
    private javax.swing.JPanel jpJob;
    private javax.swing.JPanel jpMfg;
    private javax.swing.JPanel jpMfgProd;
    private javax.swing.JPanel jpMfgProdData;
    private javax.swing.JPanel jpQty;
    private javax.swing.JPanel jpReqment;
    private javax.swing.JPanel jpSts;
    private javax.swing.JPanel jpTestApps;
    private javax.swing.JPanel jpTestAppsResults;
    private javax.swing.JPanel jpVariables;
    private javax.swing.JTextField jtfConsumpItem;
    private javax.swing.JTextField jtfConsumpType;
    private javax.swing.JTextField jtfJobNumber;
    private javax.swing.JTextField jtfJobSeries;
    private javax.swing.JTextField jtfJobStatus;
    private javax.swing.JTextField jtfTestApp;
    private javax.swing.JTextField jtfTestAppResults;
    private javax.swing.JTabbedPane jtpJob;
    private sba.lib.gui.bean.DBeanFieldBoolean moBoolConsumpRework;
    private sba.lib.gui.bean.DBeanCompoundField moCompConsumpMass;
    private sba.lib.gui.bean.DBeanCompoundField moCompConsumpQuantity;
    private sba.lib.gui.bean.DBeanCompoundField moCompJobConsumpMass;
    private sba.lib.gui.bean.DBeanCompoundField moCompJobFormulaMass;
    private sba.lib.gui.bean.DBeanCompoundField moCompJobFormulaQuantity;
    private sba.lib.gui.bean.DBeanCompoundField moCompJobJobQuantity;
    private sba.lib.gui.bean.DBeanCompoundField moCompJobMfgProdMass;
    private sba.lib.gui.bean.DBeanCompoundField moCompJobMfgProdQuantity;
    private sba.lib.gui.bean.DBeanCompoundField moCompJobReqmentMass;
    private sba.lib.gui.bean.DBeanCompoundField moCompMfgProdMass;
    private sba.lib.gui.bean.DBeanCompoundField moCompMfgProdQuantity;
    private sba.lib.gui.bean.DBeanFieldDate moDateJobDate;
    private sba.lib.gui.bean.DBeanFieldDate moDateTestAppDate;
    private sba.lib.gui.bean.DBeanFieldDecimal moDecJobLoads;
    private sba.lib.gui.bean.DBeanFieldDecimal moDecJobPackingFactor;
    private sba.lib.gui.bean.DBeanFieldKey moKeyConsumpItem;
    private sba.lib.gui.bean.DBeanFieldKey moKeyConsumpItemType;
    private sba.lib.gui.bean.DBeanFieldKey moKeyJobDepart;
    private sba.lib.gui.bean.DBeanFieldKey moKeyJobFamily;
    private sba.lib.gui.bean.DBeanFieldKey moKeyJobFormula;
    private sba.lib.gui.bean.DBeanFieldKey moKeyJobItem;
    private sba.lib.gui.bean.DBeanFieldKey moKeyJobItemType;
    private sba.lib.gui.bean.DBeanFieldKey moKeyJobLine;
    private sba.lib.gui.bean.DBeanFieldKey moKeyMfgProdItem;
    private sba.lib.gui.bean.DBeanFieldKey moKeyMfgProdItemType;
    private sba.lib.gui.bean.DBeanFieldKey moKeyTest;
    private sba.lib.gui.bean.DBeanFieldText moTextConsumpLot;
    private sba.lib.gui.bean.DBeanFieldText moTextJobLot;
    private sba.lib.gui.bean.DBeanFieldDatetime moTimeJobTimeEnd;
    private sba.lib.gui.bean.DBeanFieldDatetime moTimeJobTimeStart;
    // End of variables declaration//GEN-END:variables

    /*
     * Private methods
     */

    private void initComponentsCustom() {
        String mass = DCfgUtils.getMassUnitCode(miClient.getSession());
        
        DGuiUtils.setWindowBounds(this, 1040, 650);
        
        moDateJobDate.setDateSettings(miClient, DGuiUtils.getLabelName(jlJobDate), true);
        moKeyJobItemType.setKeySettings(miClient, DGuiUtils.getLabelName(jlJobItemType), true);
        moKeyJobFamily.setKeySettings(miClient, DGuiUtils.getLabelName(jlJobFamily), true);
        moKeyJobItem.setKeySettings(miClient, DGuiUtils.getLabelName(jlJobItem), true);
        moKeyJobFormula.setKeySettings(miClient, DGuiUtils.getLabelName(jlJobFormula), true);
        moCompJobFormulaQuantity.setCompoundFieldSettings(miClient);
        moCompJobFormulaQuantity.getField().setDecimalSettings(DGuiUtils.getLabelName(jlJobFormulaQuantity), DGuiConsts.GUI_TYPE_DEC_QTY, true);
        moCompJobFormulaMass.setCompoundFieldSettings(miClient);
        moCompJobFormulaMass.getField().setDecimalSettings(DGuiUtils.getLabelName(moCompJobFormulaMass.getToolTipText()), DGuiConsts.GUI_TYPE_DEC_QTY, true);
        moDecJobLoads.setDecimalSettings(DGuiUtils.getLabelName(jlJobLoads), DGuiConsts.GUI_TYPE_DEC_QTY, true);
        moCompJobJobQuantity.setCompoundFieldSettings(miClient);
        moCompJobJobQuantity.getField().setDecimalSettings(DGuiUtils.getLabelName(jlJobJobQuantity), DGuiConsts.GUI_TYPE_DEC_QTY, true);
        moCompJobMfgProdQuantity.setCompoundFieldSettings(miClient);
        moCompJobMfgProdQuantity.getField().setDecimalSettings(DGuiUtils.getLabelName(jlJobMfgProdQuantity), DGuiConsts.GUI_TYPE_DEC_QTY, true);
        moKeyJobDepart.setKeySettings(miClient, DGuiUtils.getLabelName(jlJobDepart), true);
        moKeyJobLine.setKeySettings(miClient, DGuiUtils.getLabelName(jlJobLine), true);
        moTextJobLot.setTextSettings(DGuiUtils.getLabelName(jlJobLot), 25);
        moTimeJobTimeStart.setDateSettings(miClient, DGuiUtils.getLabelName(jlJobTimeStart), true);
        moTimeJobTimeEnd.setDateSettings(miClient, DGuiUtils.getLabelName(jlJobTimeEnd), true);
        moDecJobPackingFactor.setDecimalSettings(DGuiUtils.getLabelName(jlJobPackingFactor), DGuiConsts.GUI_TYPE_DEC_QTY, true);
        moCompJobReqmentMass.setCompoundFieldSettings(miClient);
        moCompJobReqmentMass.getField().setDecimalSettings(DGuiUtils.getLabelName(jlJobReqmentMass), DGuiConsts.GUI_TYPE_DEC_QTY, true);
        moCompJobConsumpMass.setCompoundFieldSettings(miClient);
        moCompJobConsumpMass.getField().setDecimalSettings(DGuiUtils.getLabelName(jlJobConsumpMass), DGuiConsts.GUI_TYPE_DEC_QTY, true);
        moCompJobMfgProdMass.setCompoundFieldSettings(miClient);
        moCompJobMfgProdMass.getField().setDecimalSettings(DGuiUtils.getLabelName(jlJobMfgProdMass), DGuiConsts.GUI_TYPE_DEC_QTY, true);
        
        moFields.addField(moDateJobDate);
        moFields.addField(moKeyJobItemType);
        moFields.addField(moKeyJobFamily);
        moFields.addField(moKeyJobItem);
        moFields.addField(moKeyJobFormula);
        //moFields.addField(moCompJobFormulaQuantity.getField());
        //moFields.addField(moCompJobFormulaMass.getField());
        moFields.addField(moDecJobLoads);
        //moFields.addField(moCompJobJobQuantity.getField());
        //moFields.addField(moCompJobMfgProdQuantity.getField());
        moFields.addField(moKeyJobDepart);
        moFields.addField(moKeyJobLine);
        moFields.addField(moTextJobLot);
        moFields.addField(moTimeJobTimeStart);
        moFields.addField(moTimeJobTimeEnd);
        //moFields.addField(moDecJobPackingFactor);
        //moFields.addField(moCompJobReqmentMass.getField());
        //moFields.addField(moCompJobConsumpMass.getField());
        //moFields.addField(moCompJobMfgProdMass.getField());
        
        moFields.setFormButton(jbSave);
        
        moKeyConsumpItemType.setKeySettings(miClient, DGuiUtils.getLabelName(jlConsumpItemType), true);
        moKeyConsumpItemType.setTab(0);
        moKeyConsumpItem.setKeySettings(miClient, DGuiUtils.getLabelName(jlConsumpItem), true);
        moKeyConsumpItem.setTab(0);
        moCompConsumpQuantity.setCompoundFieldSettings(miClient);
        moCompConsumpQuantity.getField().setDecimalSettings(DGuiUtils.getLabelName(jlConsumpQuantity), DGuiConsts.GUI_TYPE_DEC_QTY, true);
        moCompConsumpQuantity.getField().setTab(0);
        moCompConsumpMass.setCompoundFieldSettings(miClient);
        moCompConsumpMass.getField().setDecimalSettings(moCompConsumpMass.getField().getComponent().getToolTipText(), DGuiConsts.GUI_TYPE_DEC_QTY, true);
        moCompConsumpMass.getField().setTab(0);
        moTextConsumpLot.setTextSettings(DGuiUtils.getLabelName(jlConsumpLot), 25);
        moTextConsumpLot.setTab(0);
        moBoolConsumpRework.setBooleanSettings(moBoolConsumpRework.getText(), false);
        moBoolConsumpRework.setTab(0);
        
        moFieldsConsump = new DGuiFields(jtpJob);
        moFieldsConsump.addField(moKeyConsumpItemType);
        moFieldsConsump.addField(moKeyConsumpItem);
        moFieldsConsump.addField(moCompConsumpQuantity.getField());
        moFieldsConsump.addField(moCompConsumpMass.getField());
        moFieldsConsump.addField(moTextConsumpLot);
        moFieldsConsump.addField(moBoolConsumpRework);
        
        moFieldsConsump.setFormButton(jbConsumpAdd);
        
        moKeyMfgProdItemType.setKeySettings(miClient, DGuiUtils.getLabelName(jlMfgProdItemType), true);
        moKeyMfgProdItemType.setTab(0);
        moKeyMfgProdItem.setKeySettings(miClient, DGuiUtils.getLabelName(jlMfgProdItem), true);
        moKeyMfgProdItem.setTab(0);
        moCompMfgProdQuantity.setCompoundFieldSettings(miClient);
        moCompMfgProdQuantity.getField().setDecimalSettings(DGuiUtils.getLabelName(jlMfgProdQuantity), DGuiConsts.GUI_TYPE_DEC_QTY, true);
        moCompMfgProdQuantity.getField().setTab(0);
        moCompMfgProdMass.setCompoundFieldSettings(miClient);
        moCompMfgProdMass.getField().setDecimalSettings(moCompMfgProdMass.getField().getComponent().getToolTipText(), DGuiConsts.GUI_TYPE_DEC_QTY, true);
        moCompMfgProdMass.getField().setTab(0);
        
        moFieldsMfgProd = new DGuiFields();
        moFieldsMfgProd.addField(moKeyMfgProdItemType);
        moFieldsMfgProd.addField(moKeyMfgProdItem);
        moFieldsMfgProd.addField(moCompMfgProdQuantity.getField());
        moFieldsMfgProd.addField(moCompMfgProdMass.getField());
        
        moFieldsMfgProd.setFormButton(jbMfgProdAdd);
        
        moKeyTest.setKeySettings(miClient, DGuiUtils.getLabelName(jlTest), true);
        moDateTestAppDate.setDateSettings(miClient, DGuiUtils.getLabelName(jlTestAppDate), true);
        
        moFieldsTestApp = new DGuiFields();
        moFieldsTestApp.addField(moKeyTest);
        moFieldsTestApp.addField(moDateTestAppDate);
        
        moFieldsTestApp.setFormButton(jbTestAppAdd);
        
        moCompJobFormulaQuantity.setEditable(false);
        moCompJobFormulaMass.setEditable(false);
        moCompJobJobQuantity.setEditable(false);
        moCompJobMfgProdQuantity.setEditable(false);
        moDecJobPackingFactor.setEditable(false);
        moCompJobReqmentMass.setEditable(false);
        moCompJobConsumpMass.setEditable(false);
        moCompJobMfgProdMass.setEditable(false);
        
        moCompJobFormulaMass.setCompoundText(mass);
        moCompJobReqmentMass.setCompoundText(mass);
        moCompJobConsumpMass.setCompoundText(mass);
        moCompJobMfgProdMass.setCompoundText(mass);
        moCompConsumpMass.setCompoundText(mass);
        moCompMfgProdMass.setCompoundText(mass);
        
        msCompTypeNameItm = (String) miClient.getSession().readField(DModConsts.MS_CMP_TP, new int[] { DModSysConsts.MS_CMP_TP_ITM }, DDbRegistry.FIELD_NAME);
        msCompTypeNameFam = (String) miClient.getSession().readField(DModConsts.MS_CMP_TP, new int[] { DModSysConsts.MS_CMP_TP_FAM }, DDbRegistry.FIELD_NAME);
        
        moMapStatus = new HashMap<>();
        moMapStatus.put(DModSysConsts.MS_JOB_ST_PEN, (String) miClient.getSession().readField(DModConsts.MS_JOB_ST, new int[] { DModSysConsts.MS_JOB_ST_PEN }, DDbRegistry.FIELD_NAME));
        moMapStatus.put(DModSysConsts.MS_JOB_ST_PRC, (String) miClient.getSession().readField(DModConsts.MS_JOB_ST, new int[] { DModSysConsts.MS_JOB_ST_PRC }, DDbRegistry.FIELD_NAME));
        moMapStatus.put(DModSysConsts.MS_JOB_ST_FIN, (String) miClient.getSession().readField(DModConsts.MS_JOB_ST, new int[] { DModSysConsts.MS_JOB_ST_FIN }, DDbRegistry.FIELD_NAME));
        
        maConsumps = new ArrayList<>();
        maTestApps = new ArrayList<>();
        
        moGridReqments = new DGridPaneForm(miClient, mnFormType, DModConsts.M_JOB_REQ, msTitle) {
            
            @Override
            public void initGrid() {
                setRowButtonsEnabled(false);
            }
            
            @Override
            public void createGridColumns() {
                int col = 0;
                DGridColumnForm[] columns = new DGridColumnForm[8];

                columns[col++] = new DGridColumnForm(DGridConsts.COL_TYPE_INT_1B, "# componente");
                columns[col++] = new DGridColumnForm(DGridConsts.COL_TYPE_TEXT_NAME_ITM_S, DGridConsts.COL_TITLE_NAME + " componente");
                columns[col++] = new DGridColumnForm(DGridConsts.COL_TYPE_DEC_QTY, "Cant requerida");
                columns[col++] = new DGridColumnForm(DGridConsts.COL_TYPE_TEXT_CODE_UNT, "Unidad medida");
                columns[col++] = new DGridColumnForm(DGridConsts.COL_TYPE_DEC_QTY, "Cant consumida");
                columns[col++] = new DGridColumnForm(DGridConsts.COL_TYPE_TEXT_CODE_CAT, DGridConsts.COL_TITLE_TYPE + " componente");
                columns[col++] = new DGridColumnForm(DGridConsts.COL_TYPE_TEXT_CODE_CAT, DGridConsts.COL_TITLE_TYPE + " ítem");
                columns[col++] = new DGridColumnForm(DGridConsts.COL_TYPE_BOOL_M, "Estándar");

                for (col = 0; col < columns.length; col++) {
                    moModel.getGridColumns().add(columns[col]);
                }
            }
        };
        
        moGridConsumps = new DGridPaneForm(miClient, mnFormType, DModConsts.M_JOB_CON, msTitle) {
            
            @Override
            public void initGrid() {
                setRowButtonsEnabled(false);
            }
            
            @Override
            public void createGridColumns() {
                int col = 0;
                DGridColumnForm[] columns = new DGridColumnForm[5];

                columns[col++] = new DGridColumnForm(DGridConsts.COL_TYPE_TEXT_NAME_ITM_S, DGridConsts.COL_TITLE_NAME + " insumo");
                columns[col++] = new DGridColumnForm(DGridConsts.COL_TYPE_DEC_QTY, "Cant consumida");
                columns[col++] = new DGridColumnForm(DGridConsts.COL_TYPE_TEXT_CODE_UNT, "Unidad medida");
                columns[col++] = new DGridColumnForm(DGridConsts.COL_TYPE_DEC_QTY, "Masa consumida (" + mass + ")");
                columns[col++] = new DGridColumnForm(DGridConsts.COL_TYPE_TEXT, "Lote");

                for (col = 0; col < columns.length; col++) {
                    moModel.getGridColumns().add(columns[col]);
                }
            }
        };
        
        moGridMfgProds = new DGridPaneForm(miClient, mnFormType, DModConsts.M_JOB_MFG, msTitle) {
            
            @Override
            public void initGrid() {
                setRowButtonsEnabled(false);
            }
            
            @Override
            public void createGridColumns() {
                int col = 0;
                DGridColumnForm[] columns = new DGridColumnForm[4];

                columns[col++] = new DGridColumnForm(DGridConsts.COL_TYPE_TEXT_NAME_ITM_S, DGridConsts.COL_TITLE_NAME + " producto");
                columns[col++] = new DGridColumnForm(DGridConsts.COL_TYPE_DEC_QTY, "Cant producida");
                columns[col++] = new DGridColumnForm(DGridConsts.COL_TYPE_TEXT_CODE_UNT, "Unidad medida");
                columns[col++] = new DGridColumnForm(DGridConsts.COL_TYPE_DEC_QTY, "Masa producida (" + mass + ")");

                for (col = 0; col < columns.length; col++) {
                    moModel.getGridColumns().add(columns[col]);
                }
            }
        };
        
        moGridVariables = new DGridPaneForm(miClient, mnFormType, DModConsts.M_JOB_VAR, msTitle) {
            
            @Override
            public void initGrid() {
                setRowButtonsEnabled(false);
            }
            
            @Override
            public void createGridColumns() {
                int col = 0;
                DGridColumnForm[] columns = new DGridColumnForm[3];

                columns[col++] = new DGridColumnForm(DGridConsts.COL_TYPE_TEXT_NAME_CAT_S, DGridConsts.COL_TITLE_NAME + " variable");
                columns[col] = new DGridColumnForm(DGridConsts.COL_TYPE_DEC_QTY, "Valor", new DGridCellRendererNumberVariable());
                columns[col++].setEditable(true);
                columns[col++] = new DGridColumnForm(DGridConsts.COL_TYPE_TEXT_CODE_UNT, "Unidad medida");

                for (col = 0; col < columns.length; col++) {
                    moModel.getGridColumns().add(columns[col]);
                }
            }
        };
        
        moGridTestApps = new DGridPaneForm(miClient, mnFormType, DModConsts.Q_APP, msTitle) {
            
            @Override
            public void initGrid() {
                setRowButtonsEnabled(false);
            }
            
            @Override
            public void createGridColumns() {
                int col = 0;
                DGridColumnForm[] columns = new DGridColumnForm[4];

                columns[col++] = new DGridColumnForm(DGridConsts.COL_TYPE_INT_1B, "# resultado");
                columns[col++] = new DGridColumnForm(DGridConsts.COL_TYPE_TEXT_NAME_CAT_S, DGridConsts.COL_TITLE_NAME + " variable");
                columns[col] = new DGridColumnForm(DGridConsts.COL_TYPE_DEC_QTY, "Valor", new DGridCellRendererNumberVariable());
                columns[col++].setEditable(true);
                columns[col++] = new DGridColumnForm(DGridConsts.COL_TYPE_TEXT_CODE_UNT, "Unidad medida");

                for (col = 0; col < columns.length; col++) {
                    moModel.getGridColumns().add(columns[col]);
                }
            }
        };
        
        moGridTestAppsResults = new DGridPaneForm(miClient, mnFormType, DModConsts.Q_APP_RES, msTitle) {
            
            @Override
            public void initGrid() {
                setRowButtonsEnabled(false);
            }
            
            @Override
            public void createGridColumns() {
                int col = 0;
                DGridColumnForm[] columns = new DGridColumnForm[4];

                columns[col++] = new DGridColumnForm(DGridConsts.COL_TYPE_INT_1B, "# resultado");
                columns[col++] = new DGridColumnForm(DGridConsts.COL_TYPE_TEXT_NAME_CAT_S, DGridConsts.COL_TITLE_NAME + " variable");
                columns[col++] = new DGridColumnForm(DGridConsts.COL_TYPE_DEC_QTY, "Valor", new DGridCellRendererNumberVariable());
                columns[col++] = new DGridColumnForm(DGridConsts.COL_TYPE_TEXT_CODE_UNT, "Unidad medida");

                for (col = 0; col < columns.length; col++) {
                    moModel.getGridColumns().add(columns[col]);
                }
            }
        };
        
        moGridReqments.setPaneFormOwner(this);
        moGridConsumps.setPaneFormOwner(this);
        moGridMfgProds.setPaneFormOwner(this);
        moGridVariables.setPaneFormOwner(this);
        moGridTestApps.setPaneFormOwner(this);
        moGridTestAppsResults.setPaneFormOwner(this);
        
        jpReqment.add(moGridReqments, BorderLayout.CENTER);
        jpConsump.add(moGridConsumps, BorderLayout.CENTER);
        jpMfgProd.add(moGridMfgProds, BorderLayout.CENTER);
        jpVariables.add(moGridVariables, BorderLayout.CENTER);
        jpTestApps.add(moGridTestApps, BorderLayout.CENTER);
        jpTestAppsResults.add(moGridTestAppsResults, BorderLayout.CENTER);
        
        mvFormGrids.add(moGridReqments);
        mvFormGrids.add(moGridConsumps);
        mvFormGrids.add(moGridMfgProds);
        mvFormGrids.add(moGridVariables);
        mvFormGrids.add(moGridTestApps);
        mvFormGrids.add(moGridTestAppsResults);
        
        moKeyGroupJobFormula = new DGuiFieldKeyGroup(miClient);
        moKeyGroupJobLine = new DGuiFieldKeyGroup(miClient);
        moKeyGroupConsumpItem = new DGuiFieldKeyGroup(miClient);
        moKeyGroupMfgProdItem = new DGuiFieldKeyGroup(miClient);
    }
    
    private void renderJobFormula() {
        if (moFormula == null) {
            moCompJobFormulaQuantity.getField().resetField();
            moCompJobFormulaMass.getField().resetField();
            moDecJobLoads.resetField();
            
            moCompJobFormulaQuantity.setCompoundText("");
            moCompJobJobQuantity.setCompoundText("");
            moCompJobMfgProdQuantity.setCompoundText("");
        }
        else {
            moCompJobFormulaQuantity.getField().setValue(moFormula.getQuantity());
            moCompJobFormulaMass.getField().setValue(moFormula.getMass_r());
            moDecJobLoads.setValue(1d);
            
            moCompJobFormulaQuantity.setCompoundText(moFormula.getRegUnit().getCode());
            moCompJobJobQuantity.setCompoundText(moFormula.getRegUnit().getCode());
            moCompJobMfgProdQuantity.setCompoundText(moFormula.getRegUnit().getCode());
        }
        
        computeJobQuantity();
    }
    
    private void renderItemConsump() {
        if (moItemConsump == null) {
            moCompConsumpQuantity.setCompoundText("");
        }
        else {
            moCompConsumpQuantity.setCompoundText(moItemConsump.getRegUnit().getCode());
        }
    }
    
    private void renderItemMfgProd() {
        if (moItemMfgProd == null) {
            moCompMfgProdQuantity.setCompoundText("");
        }
        else {
            moCompMfgProdQuantity.setCompoundText(moItemMfgProd.getRegUnit().getCode());
        }
    }
    
    private void renderTest() {
        Vector<DGridRow> rows = new Vector<>();
        
        if (moTest == null) {
            jtfTestApp.setText("");
            moDateTestAppDate.resetField();
        }
        else {
            jtfTestApp.setText("" + moTest.getAuxResultsApps() + "/" + moTest.getAuxResults());
            moDateTestAppDate.setValue(miClient.getSession().getWorkingDate());
            
            for (DDbTestVariable testVariable : moTest.getChildVariables()) {
                DDbTestAppResult testAppResult = new DDbTestAppResult();
                
                //result.setPkAppId(...);
                testAppResult.setPkVariableId(testVariable.getPkVariableId());
                //result.setPkResultId(...);
                //result.setValue(...);
                
                testAppResult.setRegVariable(testVariable.getRegVariable());
                
                rows.add(testAppResult);
            }
        }
        
        moGridTestApps.populateGrid(rows);
    }
    
    private void createGridReqmentItems() throws Exception {
        Vector<DGridRow> rows = new Vector<>();
        
        moGridReqments.clearGridRows();
        
        if (moFormula != null) {
            for (DDbFormulaComp comp : moFormula.getChildComps()) {
                rows.add(comp.createJobReqment(moDecJobLoads.getValue()));
            }
            
            moGridReqments.populateGrid(rows, this);
        }
    }
    
    private void createGridVariableItems() throws Exception {
        Vector<DGridRow> rows = new Vector<>();
        ArrayList<DDbVariable> variables = DMfgUtils.readVariables(miClient.getSession(), moFormula.getRegItem().getPkItemId());
        
        moGridVariables.clearGridRows();
        
        if (!variables.isEmpty()) {
            for (DDbVariable variable : variables) {
                DDbJobVariable jobVariable = new DDbJobVariable();
                
                //jobVariable.setPkJobId(...);
                jobVariable.setPkVariableId(variable.getPkVariableId());
                //jobVariable.setValue(...);
                
                jobVariable.setRegVariable(variable);
                
                rows.add(jobVariable);
            }
            
            moGridVariables.populateGrid(rows, this);
        }
    }
    
    private void updateFieldsJobStatus() {
        jtfConsumpType.setText("");
        jtfConsumpItem.setText("");
        moKeyConsumpItemType.resetField();
        moKeyConsumpItem.resetField();
        moCompConsumpQuantity.getField().resetField();
        moCompConsumpMass.getField().resetField();
        moTextConsumpLot.resetField();
        moBoolConsumpRework.resetField();
        moKeyMfgProdItemType.resetField();
        moKeyMfgProdItem.resetField();
        moCompMfgProdQuantity.getField().resetField();
        moCompMfgProdMass.getField().resetField();
        
        moKeyTest.removeAllItems();
        
        jtfJobStatus.setText(moMapStatus.get(mnJobStatus));
        jtfJobStatus.setCaretPosition(0);
        
        switch (mnJobStatus) {
            case DModSysConsts.MS_JOB_ST_PEN:
                moDateJobDate.setEditable(true);
                moKeyJobItemType.setEnabled(true);
                moKeyJobFamily.setEnabled(moKeyJobFamily.getSelectedIndex() > 0);
                moKeyJobItem.setEnabled(moKeyJobItem.getSelectedIndex() > 0);
                moKeyJobFormula.setEnabled(moKeyJobFormula.getSelectedIndex() > 0);
                moDecJobLoads.setEditable(true);
                moKeyJobDepart.setEnabled(true);
                moKeyJobLine.setEnabled(moKeyJobLine.getSelectedIndex() > 0);
                moTextJobLot.setEditable(false);
                moTimeJobTimeStart.setEditable(false);
                moTimeJobTimeEnd.setEditable(false);
                
                moKeyConsumpItemType.setEnabled(false);
                moCompConsumpQuantity.getField().setEditable(false);
                moCompConsumpMass.getField().setEditable(false);
                moTextConsumpLot.setEditable(false);
                moBoolConsumpRework.setEnabled(false);
                moKeyMfgProdItemType.setEnabled(false);
                moCompMfgProdQuantity.getField().setEditable(false);
                moCompMfgProdMass.getField().setEditable(false);
                moGridConsumps.setRowButtonsEnabled(false);
                moGridMfgProds.setRowButtonsEnabled(false);
                
                jbJobGenerateLot.setEnabled(false);
                jbConsumpNew.setEnabled(false);
                jbConsumpAdd.setEnabled(false);
                jbConsumpClear.setEnabled(false);
                jbMfgProdNew.setEnabled(false);
                jbMfgProdAdd.setEnabled(false);
                jbMfgProdClear.setEnabled(false);
                
                moKeyTest.setEnabled(false);
                moDateTestAppDate.setEnabled(false);
                
                jbVariablesClear.setEnabled(false);
                jbTestAppAdd.setEnabled(false);
                jbTestAppClear.setEnabled(false);
                jbTestAppResultsDelete.setEnabled(false);
                
                jbJobGoStatusNext.setEnabled(true);
                jbJobGoStatusPrev.setEnabled(false);
                break;
                
            case DModSysConsts.MS_JOB_ST_PRC:
                moDateJobDate.setEditable(false);
                moKeyJobItemType.setEnabled(false);
                moKeyJobFamily.setEnabled(false);
                moKeyJobItem.setEnabled(false);
                moKeyJobFormula.setEnabled(false);
                moDecJobLoads.setEditable(false);
                moKeyJobDepart.setEnabled(false);
                moKeyJobLine.setEnabled(false);
                moTextJobLot.setEditable(true);
                moTimeJobTimeStart.setEditable(true);
                moTimeJobTimeEnd.setEditable(true);
                
                moKeyConsumpItemType.setEnabled(true);
                moCompConsumpQuantity.getField().setEditable(true);
                moCompConsumpMass.getField().setEditable(true);
                moTextConsumpLot.setEditable(true);
                moBoolConsumpRework.setEnabled(true);
                moKeyMfgProdItemType.setEnabled(true);
                moCompMfgProdQuantity.getField().setEditable(true);
                moCompMfgProdMass.getField().setEditable(true);
                moGridConsumps.setRowButtonsEnabled(false, false, true);
                moGridMfgProds.setRowButtonsEnabled(false, false, true);
                
                jbJobGenerateLot.setEnabled(true);
                jbConsumpNew.setEnabled(true);
                jbConsumpAdd.setEnabled(true);
                jbConsumpClear.setEnabled(true);
                jbMfgProdNew.setEnabled(true);
                jbMfgProdAdd.setEnabled(true);
                jbMfgProdClear.setEnabled(true);
                
                moKeyTest.setEnabled(true);
                moDateTestAppDate.setEnabled(true);
                
                jbVariablesClear.setEnabled(true);
                jbTestAppAdd.setEnabled(true);
                jbTestAppClear.setEnabled(true);
                jbTestAppResultsDelete.setEnabled(true);
                
                jbJobGoStatusNext.setEnabled(true);
                jbJobGoStatusPrev.setEnabled(true);
                break;
                
            case DModSysConsts.MS_JOB_ST_FIN:
                moDateJobDate.setEditable(false);
                moKeyJobItemType.setEnabled(false);
                moKeyJobFamily.setEnabled(false);
                moKeyJobItem.setEnabled(false);
                moKeyJobFormula.setEnabled(false);
                moDecJobLoads.setEditable(false);
                moKeyJobDepart.setEnabled(false);
                moKeyJobLine.setEnabled(false);
                moTextJobLot.setEditable(false);
                moTimeJobTimeStart.setEditable(false);
                moTimeJobTimeEnd.setEditable(false);
                
                moKeyConsumpItemType.setEnabled(false);
                moCompConsumpQuantity.getField().setEditable(false);
                moCompConsumpMass.getField().setEditable(false);
                moTextConsumpLot.setEditable(false);
                moBoolConsumpRework.setEnabled(false);
                moKeyMfgProdItemType.setEnabled(false);
                moCompMfgProdQuantity.getField().setEditable(false);
                moCompMfgProdMass.getField().setEditable(false);
                moGridConsumps.setRowButtonsEnabled(false);
                moGridMfgProds.setRowButtonsEnabled(false);
                
                jbJobGenerateLot.setEnabled(false);
                jbConsumpNew.setEnabled(false);
                jbConsumpAdd.setEnabled(false);
                jbConsumpClear.setEnabled(false);
                jbMfgProdNew.setEnabled(false);
                jbMfgProdAdd.setEnabled(false);
                jbMfgProdClear.setEnabled(false);
                
                moKeyTest.setEnabled(false);
                moDateTestAppDate.setEnabled(false);
                
                jbVariablesClear.setEnabled(false);
                jbTestAppAdd.setEnabled(false);
                jbTestAppClear.setEnabled(false);
                jbTestAppResultsDelete.setEnabled(false);
                
                jbJobGoStatusNext.setEnabled(false);
                jbJobGoStatusPrev.setEnabled(true);
                break;
            default:
        }
    }
    
    private void computeJobLot() throws Exception{
        moTextJobLot.setValue(DMfgUtils.computeLot(miClient.getSession(), moDateJobDate.getValue(), moKeyJobItem.getValue()[0]));
    }
    
    private void computeJobQuantity() {
        if (moFormula == null) {
            moCompJobJobQuantity.getField().setValue(0d);
            moCompJobReqmentMass.getField().setValue(0d);
        }
        else {
            moCompJobJobQuantity.getField().setValue(moFormula.getQuantity() * moDecJobLoads.getValue());
            moCompJobReqmentMass.getField().setValue(moFormula.getMass_r()* moDecJobLoads.getValue());
        }
    }
    
    private void computeJobReqments() {
        int index = 0;
        double quantity = 0;
        DDbJobReqment reqment = null;
        
        for (DGridRow row : moGridReqments.getModel().getGridRows()) {
            quantity = 0;
            reqment = (DDbJobReqment) row;
            
            for (DDbJobConsump consump : maConsumps) {
                if (DLibUtils.compareKeys(reqment.getPrimaryKey(), consump.getUtilReqmentKey())) {
                    quantity += consump.getQuantity();
                }
            }
            
            reqment.setAuxQuantityConsump(quantity);
        }
        
        index = moGridReqments.getTable().getSelectedRow();
        moGridReqments.renderGridRows();
        moGridReqments.setSelectedGridRow(index);
    }
    
    private void computeJobConsumps() {
        double mass = 0;
        
        for (DDbJobConsump consump : maConsumps) {
            mass += consump.getMass_r();
        }
        
        moCompJobConsumpMass.getField().setValue(mass);
        moDecJobPackingFactor.setValue(moCompJobReqmentMass.getField().getValue() == 0d ? 0d : mass / moCompJobReqmentMass.getField().getValue());
        
        computeJobReqments();
    }
    
    private void computeJobMfgProds() {
        double quantity = 0;
        double mass = 0;
        
        for (DGridRow row : moGridMfgProds.getModel().getGridRows()) {
            quantity += ((DDbJobMfgProd) row).getQuantity();
            mass += ((DDbJobMfgProd) row).getMass_r();
        }
        
        moCompJobMfgProdQuantity.getField().setValue(quantity);
        moCompJobMfgProdMass.getField().setValue(mass);
    }
    
    private void computeConsumpMass() {
        if (moItemConsump == null) {
            moCompConsumpMass.getField().setValue(0d);
        }
        else {
            moCompConsumpMass.getField().setValue(moItemConsump.getMassUnit() * moCompConsumpQuantity.getField().getValue());
        }
    }
    
    private void computeMfgProdMass() {
        if (moItemMfgProd == null) {
            moCompMfgProdMass.getField().setValue(0d);
        }
        else {
            moCompMfgProdMass.getField().setValue(moItemMfgProd.getMassUnit() * moCompMfgProdQuantity.getField().getValue());
        }
    }
    
    private void actionPerformedJobGoStatusPrev() {
        if (mnJobStatus > DModSysConsts.MS_JOB_ST_PEN) {
            mnJobStatus--;
        }
        
        updateFieldsJobStatus();
        
        if (mnJobStatus == DModSysConsts.MS_JOB_ST_PEN) {
            jbJobGoStatusNext.requestFocus();
        }
    }
    
    private void actionPerformedJobGoStatusNext() {
        DGuiValidation validation = moFields.validateFields();
        
        if (!validation.isValid()) {
            DGuiUtils.computeValidation(miClient, validation);
        }
        else {
            if (mnJobStatus < DModSysConsts.MS_JOB_ST_FIN) {
                mnJobStatus++;
            }

            updateFieldsJobStatus();

            if (mnJobStatus == DModSysConsts.MS_JOB_ST_PRC) {
                try {
                    computeJobLot();
                    createGridReqmentItems();
                    createGridVariableItems();
                }
                catch (Exception e) {
                    DLibUtils.showException(this, e);
                }
            }
            else if (mnJobStatus == DModSysConsts.MS_JOB_ST_FIN) {
                jbJobGoStatusPrev.requestFocus();
            }
        }
    }
    
    private void actionPerformedJobGenerateLot() {
        try {
            computeJobLot();
            moTextJobLot.requestFocus();
        }
        catch (Exception e) {
            DLibUtils.showException(this, e);
        }
    }
    
    private void actionPerformedConsumpNew() {
        moKeyGroupConsumpItem.initGroup();
        moKeyGroupConsumpItem.addFieldKey(moKeyConsumpItemType, DModConsts.CX_ITM_TP_CMP, WIDTH, null);
        moKeyGroupConsumpItem.addFieldKey(moKeyConsumpItem, DModConsts.CX_ITM_FK_ITM_TP, WIDTH, null);
        moKeyGroupConsumpItem.populateCatalogues();
    }
    
    private void actionPerformedConsumpAdd() {
        DGuiValidation validation = moFieldsConsump.validateFields();
        DDbJobReqment reqment = (DDbJobReqment) moGridReqments.getSelectedGridRow();
        
        if (!validation.isValid()) {
            DGuiUtils.computeValidation(miClient, validation);
        }
        else {
            DDbJobConsump consump = new DDbJobConsump();
            
            //consump.setPkJobId(...);
            //consump.setPkConsumpId(...);
            consump.setQuantity(moCompConsumpQuantity.getField().getValue());
            //consump.setMassUnit(...);
            //consump.setMass_r(...);
            consump.setLot(moTextConsumpLot.getValue());
            consump.setRework(moBoolConsumpRework.getValue());
            consump.setFkReqmentJobId(reqment.getPkJobId());
            consump.setFkReqmentReqmentId(reqment.getPkReqmentId());
            consump.setFkItemId(moItemConsump.getPkItemId());
            //consump.setFkItemTypeId(...);
            //consump.setFkUnitId(...);
            
            consump.compute(miClient.getSession());
            
            maConsumps.add(consump);
            moGridConsumps.addGridRow(consump);
            moGridConsumps.renderGridRows();
            moGridConsumps.setSelectedGridRow(moGridConsumps.getTable().getRowCount() - 1);
            
            computeJobConsumps();
            actionPerformedConsumpClear();
        }
    }
    
    private void actionPerformedConsumpClear() {
        moFieldsConsump.resetFields();
        
        moCompConsumpQuantity.getField().getComponent().requestFocus();
    }
    
    private void actionPerformedMfgProdNew() {
        moFieldsMfgProd.resetFields();
        
        moKeyMfgProdItemType.setValue(moKeyJobItemType.getValue());
        moKeyMfgProdItem.setValue(moKeyJobItem.getValue());
        
        moCompMfgProdQuantity.getField().getComponent().requestFocus();
    }
    
    private void actionPerformedMfgProdAdd() {
        int[] keyItemType = null;
        int[] keyItem = null;
        
        DGuiValidation validation = moFieldsMfgProd.validateFields();
        
        if (!validation.isValid()) {
            DGuiUtils.computeValidation(miClient, validation);
        }
        else {
            DDbJobMfgProd mfgProd = new DDbJobMfgProd();
            
            //mfgProd.setPkJobId(...);
            //mfgProd.setPkMfgProdId(...);
            mfgProd.setQuantity(moCompMfgProdQuantity.getField().getValue());
            //mfgProd.setMassUnit(...);
            //mfgProd.setMass_r(...);
            mfgProd.setFkItemId(moKeyMfgProdItem.getValue()[0]);
            //consump.setFkItemTypeId(...);
            //consump.setFkUnitId(...);
            
            mfgProd.compute(miClient.getSession());
            
            moGridMfgProds.addGridRow(mfgProd);
            moGridMfgProds.renderGridRows();
            moGridMfgProds.setSelectedGridRow(moGridMfgProds.getTable().getRowCount() - 1);
            
            keyItemType = moKeyMfgProdItemType.getValue();
            keyItem = moKeyMfgProdItem.getValue();

            computeJobMfgProds();
            actionPerformedMfgProdClear();
            
            moKeyMfgProdItemType.setValue(keyItemType);
            moKeyMfgProdItem.setValue(keyItem);
        }
    }
    
    private void actionPerformedMfgProdClear() {
        moFieldsMfgProd.resetFields();
        
        moKeyMfgProdItemType.requestFocus();
    }
    
    private void actionPerformedVariablesClear() {
        int index = moGridVariables.getTable().getSelectedRow();
        
        for (DGridRow row : moGridVariables.getModel().getGridRows()) {
            ((DDbJobVariable) row).setValue(0);
        }
        
        moGridVariables.renderGridRows();
        moGridVariables.setSelectedGridRow(index);
    }
    
    private void actionPerformedTestAppAdd() {
        DGuiValidation validation = moFieldsTestApp.validateFields();
        
        if (!validation.isValid()) {
            DGuiUtils.computeValidation(miClient, validation);
        }
        else {
            DDbTestApp app = new DDbTestApp();
            
            //testApp.setPkAppId(...);
            app.setDate(moDateTestAppDate.getValue());
            //testApp.setDeleted(...);
            //testApp.setSystem(...);
            app.setFkTestId(moTest.getPkTestId());
            app.setFkTestTypeId(moTest.getFkTestTypeId());
            //testApp.setFkItemId(...);
            //testApp.setFkItemTypeId(...);
            //testApp.setFkJobId_n(...);
            
            moTest.setAuxResultsApps(moTest.getAuxResultsApps() + 1);
            
            for (DGridRow row : moGridTestApps.getModel().getGridRows()) {
                DDbTestAppResult appResult = (DDbTestAppResult) row;
                DDbTestAppResult appResultNew = new DDbTestAppResult();
                
                //appResult.setPkAppId(...);
                appResultNew.setPkVariableId(appResult.getPkVariableId());
                appResultNew.setPkResultId(moTest.getAuxResultsApps());
                appResultNew.setValue(appResult.getValue());
                
                appResultNew.setRegVariable(appResult.getRegVariable());
                
                app.getChildAppResults().add(appResultNew);
                moGridTestAppsResults.addGridRow(appResultNew);
            }
            
            maTestApps.add(app);
            moGridTestAppsResults.renderGridRows();
            moGridTestAppsResults.setSelectedGridRow(moGridTestAppsResults.getTable().getRowCount() - 1);
        }
    }
    
    private void actionPerformedTestAppClear() {
        int index = moGridTestApps.getTable().getSelectedRow();
        
        for (DGridRow row : moGridTestApps.getModel().getGridRows()) {
            ((DDbTestAppResult) row).setValue(0);
        }
        
        moGridTestApps.renderGridRows();
        moGridTestApps.setSelectedGridRow(index);
    }
    
    private void actionPerformedTestAppResultsDelete() {
        
    }
    
    private void itemStateChangedJobFormula() {
        if (moKeyJobFormula.getSelectedIndex() <= 0) {
            moFormula = null;
        }
        else {
            moFormula = (DDbFormula) miClient.getSession().readRegistry(DModConsts.MU_FRM, moKeyJobFormula.getValue());
        }
        
        renderJobFormula();
    }
    
    private void itemStateChangedConsumpItem() {
        if (moKeyConsumpItem.getSelectedIndex() <= 0) {
            moItemConsump = null;
        }
        else {
            moItemConsump = (DDbItem) miClient.getSession().readRegistry(DModConsts.CU_ITM, moKeyConsumpItem.getValue());
        }
        
        renderItemConsump();
    }
    
    private void itemStateChangedMfgProdItem() {
        if (moKeyMfgProdItem.getSelectedIndex() <= 0) {
            moItemMfgProd = null;
        }
        else {
            moItemMfgProd = (DDbItem) miClient.getSession().readRegistry(DModConsts.CU_ITM, moKeyMfgProdItem.getValue());
        }
        
        renderItemMfgProd();
    }
    
    private void itemStateChangedTest() {
        if (moKeyTest.getSelectedIndex() <= 0) {
            moTest = null;
        }
        else {
            moTest = (DDbTest) moKeyTest.getSelectedItem().getComplement();
        }
        
        renderTest();
    }
    
    private void focusLostJobLoads() {
        computeJobQuantity();
    }
    
    private void focusLostConsumpQuantity() {
        computeConsumpMass();
    }
    
    private void focusLostMfgProdQuantity() {
        computeMfgProdMass();
    }
    
    private void valueChangedReqments() {
        Vector<DGridRow> rows = new Vector<>();
        DDbJobReqment reqment = (DDbJobReqment) moGridReqments.getSelectedGridRow();
        
        /* When job requirement is selected on grid, by default hide type and item combo boxes.
         * If current requirement component type is "item", then no combo box is shown.
         * If current requirement component type is "family", then show only item combo box.
         * If "new" consumption is explicitly requested, then show both combo boxes.
         */
        
        moKeyGroupConsumpItem.initGroup();
        
        moCompConsumpQuantity.getField().resetField();
        moCompConsumpMass.getField().resetField();
        moTextConsumpLot.resetField();
        
        if (reqment == null) {
            moItemConsump = null;
            
            jtfConsumpType.setText("");
            jtfConsumpItem.setText("");
            
            moKeyConsumpItemType.setVisible(false);
            moKeyConsumpItem.setVisible(false);
            
            moKeyConsumpItemType.setEnabled(false);
            moKeyConsumpItem.setEnabled(false);
            
            moCompConsumpQuantity.setEditable(false);
            moCompConsumpMass.setEditable(false);
            moTextConsumpLot.setEditable(false);
            moBoolConsumpRework.setEnabled(false);
            
            moCompConsumpQuantity.setCompoundText("");
        }
        else {
            switch (reqment.getFkCompTypeId()) {
                case DModSysConsts.MS_CMP_TP_ITM:
                    moItemConsump = reqment.getRegItem();
                    
                    jtfConsumpType.setText(msCompTypeNameItm);
                    jtfConsumpType.setCaretPosition(0);
                    jtfConsumpItem.setText(moItemConsump.getName());
                    jtfConsumpItem.setCaretPosition(0);
                    
                    moKeyConsumpItemType.setVisible(false);
                    moKeyConsumpItem.setVisible(false);
            
                    moKeyConsumpItemType.setEnabled(false);
                    moKeyConsumpItem.setEnabled(false);

                    moCompConsumpQuantity.setEditable(true);
                    moCompConsumpMass.setEditable(true);
                    moTextConsumpLot.setEditable(true);
                    moBoolConsumpRework.setEnabled(true);
                    
                    moCompConsumpQuantity.setCompoundText(moItemConsump.getRegUnit().getCode());
                    break;
                    
                case DModSysConsts.MS_CMP_TP_FAM:
                    moItemConsump = null;
            
                    jtfConsumpType.setText(msCompTypeNameFam);
                    jtfConsumpType.setCaretPosition(0);
                    jtfConsumpItem.setText("");
                    
                    moKeyConsumpItemType.setVisible(false);
                    moKeyConsumpItem.setVisible(true);
            
                    moKeyConsumpItemType.setEnabled(false);
                    moKeyConsumpItem.setEnabled(true);

                    moCompConsumpQuantity.setEditable(true);
                    moCompConsumpMass.setEditable(true);
                    moTextConsumpLot.setEditable(true);
                    moBoolConsumpRework.setEnabled(true);
                    
                    moCompConsumpQuantity.setCompoundText("");
                    
                    miClient.getSession().populateCatalogue(moKeyConsumpItem, DModConsts.CU_ITM, DLibConsts.UNDEFINED, new DGuiParams(new int[] { reqment.getFkCompId() }));
                    break;
                    
                default:
            }
            
            for (DDbJobConsump consump : maConsumps) {
                if (DLibUtils.compareKeys(reqment.getPrimaryKey(), consump.getUtilReqmentKey())) {
                    rows.add(consump);
                }
            }
        }
        
        moGridConsumps.populateGrid(rows);
    }
    
    /*
     * Public methods
     */
    
    /*
     * Overriden methods
     */
    
    @Override
    public void addAllListeners() {
        jbJobGoStatusPrev.addActionListener(this);
        jbJobGoStatusNext.addActionListener(this);
        jbJobGenerateLot.addActionListener(this);
        jbConsumpNew.addActionListener(this);
        jbConsumpAdd.addActionListener(this);
        jbConsumpClear.addActionListener(this);
        jbMfgProdNew.addActionListener(this);
        jbMfgProdAdd.addActionListener(this);
        jbMfgProdClear.addActionListener(this);
        jbVariablesClear.addActionListener(this);
        jbTestAppAdd.addActionListener(this);
        jbTestAppClear.addActionListener(this);
        jbTestAppResultsDelete.addActionListener(this);
        moKeyJobFormula.addItemListener(this);
        moKeyConsumpItem.addItemListener(this);
        moKeyMfgProdItem.addItemListener(this);
        moKeyTest.addItemListener(this);
        moDecJobLoads.addFocusListener(this);
        moCompConsumpQuantity.getField().getComponent().addFocusListener(this);
        moCompMfgProdQuantity.getField().getComponent().addFocusListener(this);
    }

    @Override
    public void removeAllListeners() {
        jbJobGoStatusPrev.removeActionListener(this);
        jbJobGoStatusNext.removeActionListener(this);
        jbJobGenerateLot.addActionListener(this);
        jbConsumpNew.removeActionListener(this);
        jbConsumpAdd.removeActionListener(this);
        jbConsumpClear.removeActionListener(this);
        jbMfgProdNew.removeActionListener(this);
        jbMfgProdAdd.removeActionListener(this);
        jbMfgProdClear.removeActionListener(this);
        jbVariablesClear.removeActionListener(this);
        jbTestAppAdd.removeActionListener(this);
        jbTestAppClear.removeActionListener(this);
        jbTestAppResultsDelete.removeActionListener(this);
        moKeyJobFormula.removeItemListener(this);
        moKeyConsumpItem.removeItemListener(this);
        moKeyMfgProdItem.removeItemListener(this);
        moKeyTest.removeItemListener(this);
        moDecJobLoads.removeFocusListener(this);
        moCompConsumpQuantity.getField().getComponent().removeFocusListener(this);
        moCompMfgProdQuantity.getField().getComponent().removeFocusListener(this);
    }

    @Override
    public void reloadCatalogues() {
        moKeyGroupJobFormula.initGroup();
        moKeyGroupJobFormula.addFieldKey(moKeyJobItemType, DModConsts.CX_ITM_TP_PRO_MFG, DLibConsts.UNDEFINED, null);
        moKeyGroupJobFormula.addFieldKey(moKeyJobFamily, DModConsts.CU_FAM, DLibConsts.UNDEFINED, null);
        moKeyGroupJobFormula.addFieldKey(moKeyJobItem, DModConsts.CX_ITM_FK_FAM, DLibConsts.UNDEFINED, null);
        moKeyGroupJobFormula.addFieldKey(moKeyJobFormula, DModConsts.MU_FRM, DLibConsts.UNDEFINED, null);
        moKeyGroupJobFormula.populateCatalogues();
        
        moKeyGroupJobLine.initGroup();
        moKeyGroupJobLine.addFieldKey(moKeyJobDepart, DModConsts.MU_DPT, DLibConsts.UNDEFINED, null);
        moKeyGroupJobLine.addFieldKey(moKeyJobLine, DModConsts.MU_LIN, DLibConsts.UNDEFINED, null);
        moKeyGroupJobLine.populateCatalogues();
        
        moKeyGroupMfgProdItem.initGroup();
        moKeyGroupMfgProdItem.addFieldKey(moKeyMfgProdItemType, DModConsts.CX_ITM_TP_PRO_MFG_ALL, DLibConsts.UNDEFINED, null);
        moKeyGroupMfgProdItem.addFieldKey(moKeyMfgProdItem, DModConsts.CX_ITM_FK_ITM_TP, DLibConsts.UNDEFINED, null);
        moKeyGroupMfgProdItem.populateCatalogues();
    }

    @Override
    public void setRegistry(DDbRegistry registry) throws Exception {
        moRegistry = (DDbJob) registry;

        mnFormResult = DLibConsts.UNDEFINED;
        mbFirstActivation = true;

        removeAllListeners();
        reloadCatalogues();
        
        if (moRegistry.isRegistryNew()) {
            moRegistry.setDate(miClient.getSession().getWorkingDate());
            moRegistry.setTsStart_n(miClient.getSession().getWorkingDate());
            moRegistry.setTsEnd_n(miClient.getSession().getWorkingDate());
            moRegistry.setFkJobStatusId(DModSysConsts.MS_JOB_ST_PEN);
            
            moRegistry.initPrimaryKey();
            jtfRegistryKey.setText("");
        }
        else {
            jtfRegistryKey.setText(DLibUtils.textKey(moRegistry.getPrimaryKey()));
        }

        jtfJobSeries.setText((String) miClient.getSession().readField(DModConsts.MS_JOB_TP, new int[] { moRegistry.getFkJobTypeId() }, DDbRegistry.FIELD_CODE));
        jtfJobNumber.setText(DLibUtils.DecimalFormatIntegerRaw.format(moRegistry.getNumber()));
        jtfJobNumber.setCaretPosition(0);
        moDateJobDate.setValue(moRegistry.getDate());
        moKeyJobItemType.setValue(new int[] { moRegistry.getFkItemTypeId() });
        moKeyJobFamily.setValue(new int[] { moRegistry.getRegFormula() == null ? DLibConsts.UNDEFINED : moRegistry.getRegFormula().getRegItem().getFkFamilyId() });
        moKeyJobItem.setValue(new int[] { moRegistry.getFkItemId() });
        moKeyJobFormula.setValue(new int[] { moRegistry.getFkFormulaId() });
        itemStateChangedJobFormula();
        moDecJobLoads.setValue(moRegistry.getLoads());
        computeJobQuantity();
        moKeyJobDepart.setValue(new int[] { moRegistry.getFkDepartId() });
        moKeyJobLine.setValue(new int[] { moRegistry.getFkLineId() });
        moTextJobLot.setValue(moRegistry.getLot());
        moTimeJobTimeStart.setValue(moRegistry.getTsStart_n());
        moTimeJobTimeEnd.setValue(moRegistry.getTsEnd_n());
        
        maConsumps.clear();
        maConsumps.addAll(moRegistry.getChildConsumps());
        
        moGridReqments.populateGrid(new Vector<DGridRow>(moRegistry.getChildReqemnts()), this);
        moGridMfgProds.populateGrid(new Vector<DGridRow>(moRegistry.getChildMfgProds()));
        
        computeJobConsumps();
        computeJobMfgProds();
        
        renderItemConsump();
        renderItemMfgProd();
        valueChangedReqments();
        
        setFormEditable(true);
        
        mnJobStatus = moRegistry.getFkJobStatusId();
        updateFieldsJobStatus();
        
        moKeyGroupConsumpItem.resetGroup();
        moKeyGroupMfgProdItem.resetGroup();
        
        if (moRegistry.isRegistryNew()) {
            moKeyGroupJobFormula.resetGroup();
            moKeyGroupJobLine.resetGroup();
        }
        else {
            
        }
        
        addAllListeners();
    }

    @Override
    public DDbJob getRegistry() throws Exception {
        DDbJob registry = moRegistry.clone();

        if (registry.isRegistryNew()) {
            //registry.setPkJobId(...);
        }

        //registry.setNumber(...);
        registry.setDate(moDateJobDate.getValue());
        registry.setTsStart_n(moTimeJobTimeStart.getValue());
        registry.setTsEnd_n(moTimeJobTimeEnd.getValue());
        //registry.setFormulaQuantity(...); // set on save
        //registry.setFormulaMass_r(...); // set on save
        registry.setLoads(moDecJobLoads.getValue());
        //registry.setJobQuantity_r(...); // set on save
        //registry.setMfgProdQuantity_r(...); // set on save
        //registry.setReqmentMass_r(...); // set on save
        //registry.setConsumpMass_r(...); // set on save
        //registry.setMfgProdMass_r(...); // set on save
        registry.setLot(moTextJobLot.getValue());
        //registry.setPackingFactor(...);
        //registry.setDeleted(...);
        //registry.setSystem(...);
        //registry.setFkJobTypeId(...); // already set
        registry.setFkJobStatusId(mnJobStatus);
        registry.setFkDepartId(moKeyJobDepart.getValue()[0]);
        registry.setFkLineId(moKeyJobLine.getValue()[0]);
        //registry.setFkJobId_n(...); // already set, if any
        registry.setFkFormulaId(moFormula.getPkFormulaId());
        //registry.setFkFormulaTypeId(...); // set on save
        //registry.setFkItemId(...); // set on save
        //registry.setFkItemTypeId(...); // set on save
        //registry.setFkUnitId(...); // set on save
        //registry.setFkPresentId(...); // set on save

        registry.getChildReqemnts().clear();
        for (DGridRow row : moGridReqments.getModel().getGridRows()) {
            registry.getChildReqemnts().add((DDbJobReqment) row);
        }
        
        registry.getChildConsumps().clear();
        for (DDbJobConsump consump : maConsumps) {
            registry.getChildConsumps().add(consump);
        }

        registry.getChildMfgProds().clear();
        for (DGridRow row : moGridMfgProds.getModel().getGridRows()) {
            registry.getChildMfgProds().add((DDbJobMfgProd) row);
        }
        
        return registry;
    }

    @Override
    public DGuiValidation validateForm() {
        return moFields.validateFields();
    }

    @Override
    public void notifyRowNew(int gridType, int gridSubtype, int row, DGridRow gridRow) {
        throw new UnsupportedOperationException("Not supported yet.");
    }

    @Override
    public void notifyRowEdit(int gridType, int gridSubtype, int row, DGridRow gridRow) {
        throw new UnsupportedOperationException("Not supported yet.");
    }

    @Override
    public void notifyRowDelete(int gridType, int gridSubtype, int row, DGridRow gridRow) {
        if (gridType == mnFormType) {
            switch (gridSubtype) {
                case DModConsts.M_JOB_REQ:
                    break;
                case DModConsts.M_JOB_CON:
                    maConsumps.remove(gridRow);
                    /*
                    moGridConsumps.getModel().getGridRows().remove(gridRow);
                    moGridConsumps.renderGridRows();
                    moGridConsumps.setSelectedGridRow(row < moGridConsumps.getTable().getRowCount() ? row : moGridConsumps.getTable().getRowCount() - 1);
                    */
                    computeJobConsumps();
                    break;
                case DModConsts.M_JOB_MFG:
                    /*
                    moGridMfgProds.getModel().getGridRows().remove(gridRow);
                    moGridMfgProds.renderGridRows();
                    moGridMfgProds.setSelectedGridRow(row < moGridMfgProds.getTable().getRowCount() ? row : moGridMfgProds.getTable().getRowCount() - 1);
                    */
                    computeJobMfgProds();
                    break;
                default:
            }
        }
    }

    @Override
    public void actionPerformed(ActionEvent e) {
        if (e.getSource() instanceof JButton) {
            JButton button = (JButton) e.getSource();
            
            if (button == jbJobGoStatusPrev) {
                actionPerformedJobGoStatusPrev();
            }
            else if (button == jbJobGoStatusNext) {
                actionPerformedJobGoStatusNext();
            }
            else if (button == jbJobGenerateLot) {
                actionPerformedJobGenerateLot();
            }
            else if (button == jbConsumpNew) {
                actionPerformedConsumpNew();
            }
            else if (button == jbConsumpAdd) {
                actionPerformedConsumpAdd();
            }
            else if (button == jbConsumpClear) {
                actionPerformedConsumpClear();
            }
            else if (button == jbMfgProdNew) {
                actionPerformedMfgProdNew();
            }
            else if (button == jbMfgProdAdd) {
                actionPerformedMfgProdAdd();
            }
            else if (button == jbMfgProdClear) {
                actionPerformedMfgProdClear();
            }
            else if (button == jbVariablesClear) {
                actionPerformedVariablesClear();
            }
            else if (button == jbTestAppAdd) {
                actionPerformedTestAppAdd();
            }
            else if (button == jbTestAppClear) {
                actionPerformedTestAppClear();
            }
            else if (button == jbTestAppResultsDelete) {
                actionPerformedTestAppResultsDelete();
            }
        }
    }

    @Override
    public void itemStateChanged(ItemEvent e) {
        if (e.getSource() instanceof DBeanFieldKey) {
            if (e.getStateChange() == ItemEvent.SELECTED) {
                DBeanFieldKey field = (DBeanFieldKey) e.getSource();
                
                if (field == moKeyJobFormula) {
                    itemStateChangedJobFormula();
                }
                else if (field == moKeyConsumpItem) {
                    itemStateChangedConsumpItem();
                }
                else if (field == moKeyMfgProdItem) {
                    itemStateChangedMfgProdItem();
                }
                else if (field == moKeyTest) {
                    itemStateChangedTest();
                }
            }
        }
    }

    @Override
    public void focusGained(FocusEvent e) {
        
    }

    @Override
    public void focusLost(FocusEvent e) {
        if (e.getSource() instanceof DBeanFieldDecimal) {
            DBeanFieldDecimal field = (DBeanFieldDecimal) e.getSource();
            
            if (field == moDecJobLoads) {
                focusLostJobLoads();
            }
            else if (field == moCompConsumpQuantity.getField().getComponent()) {
                focusLostConsumpQuantity();
            }
            else if (field == moCompMfgProdQuantity.getField().getComponent()) {
                focusLostMfgProdQuantity();
            }
        }
    }

    @Override
    public void valueChanged(ListSelectionEvent e) {
        if (e.getSource() instanceof ListSelectionModel) {
            ListSelectionModel listSelectionModel = (ListSelectionModel) e.getSource();
            
            if (listSelectionModel == moGridReqments.getTable().getSelectionModel()) {
                valueChangedReqments();
            }
        }
    }
}
